/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/AnimalPropelledType.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> LSB of 00125 degrees
 * <BR> A range of 0 to 3599875 degrees
 * Class definition of the AnimalPropelledType type of the dsrc module.
 */
public class AnimalPropelledType extends fr.marben.asnsdk.japi.spe.ExtEnumeratedValue
{
  /**
   * value of the named enumerated unavailable.
   */
  public static final int ASN_unavailable = 0;

  /**
   * value of the named enumerated otherTypes.
   */
  public static final int ASN_otherTypes = 1;

  /**
   * value of the named enumerated animalMounted.
   */
  public static final int ASN_animalMounted = 2;

  /**
   * value of the named enumerated animalDrawnCarriage.
   */
  public static final int ASN_animalDrawnCarriage = 3;

  /**
   *  Constructs a newly allocated AnimalPropelledType.
   */
  public AnimalPropelledType ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated AnimalPropelledType that represents the primitive int argument.
   *  @param value the value to be represented by this AnimalPropelledType.
   */
  public AnimalPropelledType (int value)
  {
    super(value);
  };

  /**
   *  Constructs a newly allocated AnimalPropelledType that represents the unknownExt argument.
   *  @param unknownExt the unknown extension value to be represented by this AnimalPropelledType.
   */
  public AnimalPropelledType (fr.marben.asnsdk.japi.UnknownExtensionValue unknownExt)
  {
    super(unknownExt);
  };
}
