/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/AntiLockBrakeStatus.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the AntiLockBrakeStatus type of the dsrc module.
 */
public class AntiLockBrakeStatus extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated unavailable.
   */
  public static final int ASN_unavailable = 0;

  /**
   * value of the named enumerated off.
   */
  public static final int ASN_off = 1;

  /**
   * value of the named enumerated on.
   */
  public static final int ASN_on = 2;

  /**
   * value of the named enumerated engaged.
   */
  public static final int ASN_engaged = 3;

  /**
   *  Constructs a newly allocated AntiLockBrakeStatus.
   */
  public AntiLockBrakeStatus ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated AntiLockBrakeStatus that represents the primitive int argument.
   *  @param value the value to be represented by this AntiLockBrakeStatus.
   */
  public AntiLockBrakeStatus (int value)
  {
    super(value);
  };
}
