/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/ComputedLane.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the ComputedLane type of the dsrc module.
 */
public class ComputedLane extends fr.marben.asnsdk.japi.spe.ExtSequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 50;

  /**
   * <BR> Data needed to created a computed lane
   * mandatory field referenceLaneId.
   */
  public j2375.dsrc.asncode.dsrc.LaneID referenceLaneId;

  /**
   * <BR> the lane ID upon which this 
   * <BR> computed lane will be based 
   * <BR> Lane Offset in X and Y direction
   * mandatory field offsetXaxis.
   */
  public OffsetXaxis offsetXaxis;

  /**
   * mandatory field offsetYaxis.
   */
  public OffsetYaxis offsetYaxis;

  /**
   * <BR> A path X offset value for translations of the 
   * <BR> path's points when creating translated lanes 
   * <BR> The values found in the reference lane are 
   * <BR> all offset based on the X and Y values from 
   * <BR> the coordinates of the reference lane's 
   * <BR> initial path point   
   * <BR> Lane Rotation
   * optional field rotateXY.
   */
  public j2375.dsrc.asncode.dsrc.Angle rotateXY;

  /**
   * <BR> A path rotation value for the entire lane
   * <BR> Observe that this rotates the existing orientation 
   * <BR> of the referenced lane, it does not replace it
   * <BR> Rotation occurs about the initial path point
   * <BR> Lane Path Scale (zooming)
   * optional field scaleXaxis.
   */
  public j2375.dsrc.asncode.dsrc.Scale_B12 scaleXaxis;

  /**
   * optional field scaleYaxis.
   */
  public j2375.dsrc.asncode.dsrc.Scale_B12 scaleYaxis;

  /**
   * <BR> value for translations or zooming of the path's 
   * <BR> points The values found in the reference lane 
   * <BR> are all expanded or contracted based on the X 
   * <BR> and Y and width values from the coordinates of 
   * <BR> the reference lane's initial path point  
   * <BR> The Z axis remains untouched  
   * optional field regional.
   */
  public Regional regional;

  /**
   * class definition of the offsetXaxis field.
   */
  public static class OffsetXaxis extends fr.marben.asnsdk.japi.spe.ChoiceValue
  {
    /**
     * value of the fieldNumber for the field small.
     * <BR>Use {@link j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm} for the values of this type.
     */
    public static final short ASN_small = 0;

    /**
     * value of the fieldNumber for the field large.
     * <BR>Use {@link j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg} for the values of this type.
     */
    public static final short ASN_large = 1;

    /**
     *  Constructs a newly allocated OffsetXaxis.
     */
    public OffsetXaxis ()
    {
      super();
    };

    /**
     *  Create a newly allocated OffsetXaxis.
     *  @param fieldNumber the named type identifier of the component.
     *  @param value the value to set.
     *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
     */
     public OffsetXaxis(short fieldNumber,
                          fr.marben.asnsdk.japi.spe.Value value)
                          throws fr.marben.asnsdk.japi.InvalidStructureException
     {
       this.fieldNumber = fieldNumber;
       switch (fieldNumber)
       {
       case 0 :
         this.value = (j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm)value;
         break;
       case 1 :
         this.value = (j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg)value;
         break;
       default :
         throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
       }
     }

    /**
     *  Sets the value of a component from this OffsetXaxis.
     *  @param fieldNumber the named type identifier of the component.
     *  @param value the value to set.
     *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
     */
     public void setValue(short fieldNumber,
                          fr.marben.asnsdk.japi.spe.Value value)
                          throws fr.marben.asnsdk.japi.InvalidStructureException
     {
       this.fieldNumber = fieldNumber;
       switch (fieldNumber)
       {
       case 0 :
         this.value = (j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm)value;
         break;
       case 1 :
         this.value = (j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg)value;
         break;
       default :
         throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
       }
     }

    /**
     *  Creates and sets a newly allocated component value from this OffsetXaxis.
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this OffsetXaxis.
     *  @return a value from a class implementing the IValue interface.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnSetNewChoiceValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.IChoiceNamedType field)
     {
       this.fieldNumber = field.getFieldNumber(context);
       switch (this.fieldNumber)
       {
       case 0 :
         this.value = new j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm();
         return this.value;
       case 1 :
         this.value = new j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg();
         return this.value;
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
       }
     }

  }

  /**
   * class definition of the offsetYaxis field.
   */
  public static class OffsetYaxis extends fr.marben.asnsdk.japi.spe.ChoiceValue
  {
    /**
     * value of the fieldNumber for the field small.
     * <BR>Use {@link j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm} for the values of this type.
     */
    public static final short ASN_small = 0;

    /**
     * value of the fieldNumber for the field large.
     * <BR>Use {@link j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg} for the values of this type.
     */
    public static final short ASN_large = 1;

    /**
     *  Constructs a newly allocated OffsetYaxis.
     */
    public OffsetYaxis ()
    {
      super();
    };

    /**
     *  Create a newly allocated OffsetYaxis.
     *  @param fieldNumber the named type identifier of the component.
     *  @param value the value to set.
     *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
     */
     public OffsetYaxis(short fieldNumber,
                          fr.marben.asnsdk.japi.spe.Value value)
                          throws fr.marben.asnsdk.japi.InvalidStructureException
     {
       this.fieldNumber = fieldNumber;
       switch (fieldNumber)
       {
       case 0 :
         this.value = (j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm)value;
         break;
       case 1 :
         this.value = (j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg)value;
         break;
       default :
         throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
       }
     }

    /**
     *  Sets the value of a component from this OffsetYaxis.
     *  @param fieldNumber the named type identifier of the component.
     *  @param value the value to set.
     *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
     */
     public void setValue(short fieldNumber,
                          fr.marben.asnsdk.japi.spe.Value value)
                          throws fr.marben.asnsdk.japi.InvalidStructureException
     {
       this.fieldNumber = fieldNumber;
       switch (fieldNumber)
       {
       case 0 :
         this.value = (j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm)value;
         break;
       case 1 :
         this.value = (j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg)value;
         break;
       default :
         throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
       }
     }

    /**
     *  Creates and sets a newly allocated component value from this OffsetYaxis.
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this OffsetYaxis.
     *  @return a value from a class implementing the IValue interface.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnSetNewChoiceValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.IChoiceNamedType field)
     {
       this.fieldNumber = field.getFieldNumber(context);
       switch (this.fieldNumber)
       {
       case 0 :
         this.value = new j2375.dsrc.asncode.dsrc.DrivenLineOffsetSm();
         return this.value;
       case 1 :
         this.value = new j2375.dsrc.asncode.dsrc.DrivenLineOffsetLg();
         return this.value;
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
       }
     }

  }

  /**
   * class definition of the regional field.
   */
  public static class Regional extends fr.marben.asnsdk.japi.spe.SequenceOfValue
  {
    /**
     * class definition of the SEQUENCE field.
     */
    public static class SEQUENCE extends fr.marben.asnsdk.japi.spe.SequenceValue
    {
      /**
       * mandatory field regionId.
       */
      public j2375.dsrc.asncode.dsrc.RegionId regionId;

      /**
       * mandatory field regExtValue.
       */
      public fr.marben.asnsdk.japi.spe.OpenTypeValue regExtValue;

      /**
       *  Constructs a newly allocated SEQUENCE.
       */
      public SEQUENCE ()
      {
        super();
      };

      /**
       *  Gets the value of a component from this SEQUENCE.
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type identifier of the component.
       *  @return the value identified by the named type.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           return this.regionId;
         case 1 :
           return this.regExtValue;
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
         }
       }

      /**
       *  Creates a newly allocated component value from this SEQUENCE.
       *  this value is created for temporary use to solve atNotations
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type of this SEQUENCE.
       *  @return a value from a class implementing the IValue interface.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           return new j2375.dsrc.asncode.dsrc.RegionId();
         case 1 :
           return new fr.marben.asnsdk.japi.spe.OpenTypeValue();
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
         }
       }

      /**
       *  Creates and sets a newly allocated component value from this SEQUENCE.
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type of this SEQUENCE.
       *  @return a value from a class implementing the IValue interface.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           this.regionId = new j2375.dsrc.asncode.dsrc.RegionId();
           return this.regionId;
         case 1 :
           this.regExtValue = new fr.marben.asnsdk.japi.spe.OpenTypeValue();
           return this.regExtValue;
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
         }
       }

    }

    /**
     *  Constructs a newly allocated Regional.
     */
    public Regional ()
    {
      super();
    };

    /**
     *  Constructs a newly allocated Regional with the given list.
     *  @param list the list used to initialize this Regional.
     */
    public Regional (java.util.List list)
    {
      super(list);
    };
    
    /**
     *  Creates and appends a newly allocated component value from 
     *  this Regional.
     *  This method is only for ASNSDK internal use. 
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this Regional.
     *  @return a value from a class implementing de IValue interface.
     */
    public fr.marben.asnsdk.japi.vi.IValue asnAddNewSetSeqOfValue(
                          fr.marben.asnsdk.japi.Context context,
                          fr.marben.asnsdk.japi.vi.ISetSeqOfNamedType field)
    {
          j2375.dsrc.asncode.dsrc.ComputedLane.Regional.SEQUENCE value = new j2375.dsrc.asncode.dsrc.ComputedLane.Regional.SEQUENCE();
          this.valueList.add(value);
          return value;
    }
  }

  /**
   *  Constructs a newly allocated ComputedLane.
   */
  public ComputedLane ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this ComputedLane.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.referenceLaneId;
     case 1 :
       return this.offsetXaxis;
     case 2 :
       return this.offsetYaxis;
     case 3 :
       return this.rotateXY;
     case 4 :
       return this.scaleXaxis;
     case 5 :
       return this.scaleYaxis;
     case 6 :
       return this.regional;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this ComputedLane.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this ComputedLane.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.LaneID();
     case 1 :
       return new OffsetXaxis();
     case 2 :
       return new OffsetYaxis();
     case 3 :
       return new j2375.dsrc.asncode.dsrc.Angle();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.Scale_B12();
     case 5 :
       return new j2375.dsrc.asncode.dsrc.Scale_B12();
     case 6 :
       return new Regional();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this ComputedLane.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this ComputedLane.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.referenceLaneId = new j2375.dsrc.asncode.dsrc.LaneID();
       return this.referenceLaneId;
     case 1 :
       this.offsetXaxis = new OffsetXaxis();
       return this.offsetXaxis;
     case 2 :
       this.offsetYaxis = new OffsetYaxis();
       return this.offsetYaxis;
     case 3 :
       this.rotateXY = new j2375.dsrc.asncode.dsrc.Angle();
       return this.rotateXY;
     case 4 :
       this.scaleXaxis = new j2375.dsrc.asncode.dsrc.Scale_B12();
       return this.scaleXaxis;
     case 5 :
       this.scaleYaxis = new j2375.dsrc.asncode.dsrc.Scale_B12();
       return this.scaleYaxis;
     case 6 :
       this.regional = new Regional();
       return this.regional;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets a group value from the ComputedLane.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Returns whether or not this group is present among the extensions.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @return <code>true</code>: when the group is present.
   *          <code>false</code>: when the group is not present.
   */
   public boolean asnIsSetSeqGroupPresent(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated group value of the ComputedLane.
   *  This group is created for temporary use, in order to solve atNotations.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated group value of the ComputedLane.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 50;
  }

}
