/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/ConfidenceSet.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the ConfidenceSet type of the dsrc module.
 */
public class ConfidenceSet extends fr.marben.asnsdk.japi.spe.ExtSequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 51;

  /**
   * optional field accelConfidence.
   */
  public j2375.dsrc.asncode.dsrc.AccelSteerYawRateConfidence accelConfidence;

  /**
   * optional field speedConfidence.
   */
  public j2375.dsrc.asncode.dsrc.SpeedandHeadingandThrottleConfidence speedConfidence;

  /**
   * optional field timeConfidence.
   */
  public j2375.dsrc.asncode.dsrc.TimeConfidence timeConfidence;

  /**
   * optional field posConfidence.
   */
  public j2375.dsrc.asncode.dsrc.PositionConfidenceSet posConfidence;

  /**
   * optional field steerConfidence.
   */
  public j2375.dsrc.asncode.dsrc.SteeringWheelAngleConfidence steerConfidence;

  /**
   * optional field headingConfidence.
   */
  public j2375.dsrc.asncode.dsrc.HeadingConfidence headingConfidence;

  /**
   * optional field throttleConfidence.
   */
  public j2375.dsrc.asncode.dsrc.ThrottleConfidence throttleConfidence;

  /**
   *  Constructs a newly allocated ConfidenceSet.
   */
  public ConfidenceSet ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this ConfidenceSet.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.accelConfidence;
     case 1 :
       return this.speedConfidence;
     case 2 :
       return this.timeConfidence;
     case 3 :
       return this.posConfidence;
     case 4 :
       return this.steerConfidence;
     case 5 :
       return this.headingConfidence;
     case 6 :
       return this.throttleConfidence;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this ConfidenceSet.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this ConfidenceSet.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.AccelSteerYawRateConfidence();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.SpeedandHeadingandThrottleConfidence();
     case 2 :
       return new j2375.dsrc.asncode.dsrc.TimeConfidence();
     case 3 :
       return new j2375.dsrc.asncode.dsrc.PositionConfidenceSet();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.SteeringWheelAngleConfidence();
     case 5 :
       return new j2375.dsrc.asncode.dsrc.HeadingConfidence();
     case 6 :
       return new j2375.dsrc.asncode.dsrc.ThrottleConfidence();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this ConfidenceSet.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this ConfidenceSet.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.accelConfidence = new j2375.dsrc.asncode.dsrc.AccelSteerYawRateConfidence();
       return this.accelConfidence;
     case 1 :
       this.speedConfidence = new j2375.dsrc.asncode.dsrc.SpeedandHeadingandThrottleConfidence();
       return this.speedConfidence;
     case 2 :
       this.timeConfidence = new j2375.dsrc.asncode.dsrc.TimeConfidence();
       return this.timeConfidence;
     case 3 :
       this.posConfidence = new j2375.dsrc.asncode.dsrc.PositionConfidenceSet();
       return this.posConfidence;
     case 4 :
       this.steerConfidence = new j2375.dsrc.asncode.dsrc.SteeringWheelAngleConfidence();
       return this.steerConfidence;
     case 5 :
       this.headingConfidence = new j2375.dsrc.asncode.dsrc.HeadingConfidence();
       return this.headingConfidence;
     case 6 :
       this.throttleConfidence = new j2375.dsrc.asncode.dsrc.ThrottleConfidence();
       return this.throttleConfidence;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets a group value from the ConfidenceSet.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Returns whether or not this group is present among the extensions.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @return <code>true</code>: when the group is present.
   *          <code>false</code>: when the group is not present.
   */
   public boolean asnIsSetSeqGroupPresent(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated group value of the ConfidenceSet.
   *  This group is created for temporary use, in order to solve atNotations.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated group value of the ConfidenceSet.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 51;
  }

}
