/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/DDateTime.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the DDateTime type of the dsrc module.
 */
public class DDateTime extends fr.marben.asnsdk.japi.spe.SequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 61;

  /**
   * optional field year.
   */
  public j2375.dsrc.asncode.dsrc.DYear year;

  /**
   * optional field month.
   */
  public j2375.dsrc.asncode.dsrc.DMonth month;

  /**
   * optional field day.
   */
  public j2375.dsrc.asncode.dsrc.DDay day;

  /**
   * optional field hour.
   */
  public j2375.dsrc.asncode.dsrc.DHour hour;

  /**
   * optional field minute.
   */
  public j2375.dsrc.asncode.dsrc.DMinute minute;

  /**
   * optional field second.
   */
  public j2375.dsrc.asncode.dsrc.DSecond second;

  /**
   * optional field offset.
   */
  public j2375.dsrc.asncode.dsrc.DOffset offset;

  /**
   *  Constructs a newly allocated DDateTime.
   */
  public DDateTime ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this DDateTime.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.year;
     case 1 :
       return this.month;
     case 2 :
       return this.day;
     case 3 :
       return this.hour;
     case 4 :
       return this.minute;
     case 5 :
       return this.second;
     case 6 :
       return this.offset;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this DDateTime.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this DDateTime.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.DYear();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.DMonth();
     case 2 :
       return new j2375.dsrc.asncode.dsrc.DDay();
     case 3 :
       return new j2375.dsrc.asncode.dsrc.DHour();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.DMinute();
     case 5 :
       return new j2375.dsrc.asncode.dsrc.DSecond();
     case 6 :
       return new j2375.dsrc.asncode.dsrc.DOffset();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this DDateTime.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this DDateTime.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.year = new j2375.dsrc.asncode.dsrc.DYear();
       return this.year;
     case 1 :
       this.month = new j2375.dsrc.asncode.dsrc.DMonth();
       return this.month;
     case 2 :
       this.day = new j2375.dsrc.asncode.dsrc.DDay();
       return this.day;
     case 3 :
       this.hour = new j2375.dsrc.asncode.dsrc.DHour();
       return this.hour;
     case 4 :
       this.minute = new j2375.dsrc.asncode.dsrc.DMinute();
       return this.minute;
     case 5 :
       this.second = new j2375.dsrc.asncode.dsrc.DSecond();
       return this.second;
     case 6 :
       this.offset = new j2375.dsrc.asncode.dsrc.DOffset();
       return this.offset;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 61;
  }

}
