/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/DeltaTime.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> With an angle range from 
 * <BR> negative 150 to positive 150 
 * <BR> in one degree steps where zero is directly
 * <BR> along the axis or the lane center line as defined by the
 * <BR> two closest points
 * Class definition of the DeltaTime type of the dsrc module.
 */
public class DeltaTime extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated DeltaTime.
   */
  public DeltaTime ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated DeltaTime that represents the primitive int argument.
   *  @param value the value to be represented by this DeltaTime.
   */
  public DeltaTime (int value)
  {
    super(value);
  };
}
