/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/DescriptiveName.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> Supporting a range of +/- 20 minute in steps of 10 seconds
 * <BR> the value of -121 shall be used when more than -20 minutes
 * <BR> the value of +120 shall be used when more than +20 minutes
 * <BR> the value -122 shall be used when the value is unavailable
 * Class definition of the DescriptiveName type of the dsrc module.
 */
public class DescriptiveName extends fr.marben.asnsdk.japi.spe.IA5StringValue
{
  /**
   *  Constructs a newly allocated DescriptiveName.
   */
  public DescriptiveName ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated DescriptiveName that represents the primitive string argument.
   *  @param value the value to be represented by this DescriptiveName.
   */
  public DescriptiveName (java.lang.String value)
  {
    super(value);
  };
}
