/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/DFullTime.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> time zone
 * Class definition of the DFullTime type of the dsrc module.
 */
public class DFullTime extends fr.marben.asnsdk.japi.spe.SequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 62;

  /**
   * mandatory field year.
   */
  public j2375.dsrc.asncode.dsrc.DYear year;

  /**
   * mandatory field month.
   */
  public j2375.dsrc.asncode.dsrc.DMonth month;

  /**
   * mandatory field day.
   */
  public j2375.dsrc.asncode.dsrc.DDay day;

  /**
   * mandatory field hour.
   */
  public j2375.dsrc.asncode.dsrc.DHour hour;

  /**
   * mandatory field minute.
   */
  public j2375.dsrc.asncode.dsrc.DMinute minute;

  /**
   *  Constructs a newly allocated DFullTime.
   */
  public DFullTime ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this DFullTime.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.year;
     case 1 :
       return this.month;
     case 2 :
       return this.day;
     case 3 :
       return this.hour;
     case 4 :
       return this.minute;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this DFullTime.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this DFullTime.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.DYear();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.DMonth();
     case 2 :
       return new j2375.dsrc.asncode.dsrc.DDay();
     case 3 :
       return new j2375.dsrc.asncode.dsrc.DHour();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.DMinute();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this DFullTime.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this DFullTime.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.year = new j2375.dsrc.asncode.dsrc.DYear();
       return this.year;
     case 1 :
       this.month = new j2375.dsrc.asncode.dsrc.DMonth();
       return this.month;
     case 2 :
       this.day = new j2375.dsrc.asncode.dsrc.DDay();
       return this.day;
     case 3 :
       this.hour = new j2375.dsrc.asncode.dsrc.DHour();
       return this.hour;
     case 4 :
       this.minute = new j2375.dsrc.asncode.dsrc.DMinute();
       return this.minute;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 62;
  }

}
