/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/DistanceUnits.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the DistanceUnits type of the dsrc module.
 */
public class DistanceUnits extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated centimeter.
   */
  public static final int ASN_centimeter = 0;

  /**
   * value of the named enumerated cm2_5.
   */
  public static final int ASN_cm2_5 = 1;

  /**
   * value of the named enumerated decimeter.
   */
  public static final int ASN_decimeter = 2;

  /**
   * value of the named enumerated meter.
   */
  public static final int ASN_meter = 3;

  /**
   * value of the named enumerated kilometer.
   */
  public static final int ASN_kilometer = 4;

  /**
   * value of the named enumerated foot.
   */
  public static final int ASN_foot = 5;

  /**
   * value of the named enumerated yard.
   */
  public static final int ASN_yard = 6;

  /**
   * value of the named enumerated mile.
   */
  public static final int ASN_mile = 7;

  /**
   *  Constructs a newly allocated DistanceUnits.
   */
  public DistanceUnits ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated DistanceUnits that represents the primitive int argument.
   *  @param value the value to be represented by this DistanceUnits.
   */
  public DistanceUnits (int value)
  {
    super(value);
  };
}
