/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/DOffset.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> units of months
 * Class definition of the DOffset type of the dsrc module.
 */
public class DOffset extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated DOffset.
   */
  public DOffset ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated DOffset that represents the primitive int argument.
   *  @param value the value to be represented by this DOffset.
   */
  public DOffset (int value)
  {
    super(value);
  };
}
