/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/DriveAxleTemperature.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the DriveAxleTemperature type of the dsrc module.
 */
public class DriveAxleTemperature extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated DriveAxleTemperature.
   */
  public DriveAxleTemperature ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated DriveAxleTemperature that represents the primitive int argument.
   *  @param value the value to be represented by this DriveAxleTemperature.
   */
  public DriveAxleTemperature (int value)
  {
    super(value);
  };
}
