/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/Duration.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> Hex 0xFF  
 * <BR> All other values are reserved for std use
 * Class definition of the Duration type of the dsrc module.
 */
public class Duration extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 68;

  /**
   *  Constructs a newly allocated Duration.
   */
  public Duration ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated Duration that represents the primitive int argument.
   *  @param value the value to be represented by this Duration.
   */
  public Duration (int value)
  {
    super(value);
  };
  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 68;
  }

}
