/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/ElevationConfidence.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> units of years
 * Class definition of the ElevationConfidence type of the dsrc module.
 */
public class ElevationConfidence extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated unavailable.
   */
  public static final int ASN_unavailable = 0;

  /**
   * value of the named enumerated elev_500_00.
   */
  public static final int ASN_elev_500_00 = 1;

  /**
   * value of the named enumerated elev_200_00.
   */
  public static final int ASN_elev_200_00 = 2;

  /**
   * value of the named enumerated elev_100_00.
   */
  public static final int ASN_elev_100_00 = 3;

  /**
   * value of the named enumerated elev_050_00.
   */
  public static final int ASN_elev_050_00 = 4;

  /**
   * value of the named enumerated elev_020_00.
   */
  public static final int ASN_elev_020_00 = 5;

  /**
   * value of the named enumerated elev_010_00.
   */
  public static final int ASN_elev_010_00 = 6;

  /**
   * value of the named enumerated elev_005_00.
   */
  public static final int ASN_elev_005_00 = 7;

  /**
   * value of the named enumerated elev_002_00.
   */
  public static final int ASN_elev_002_00 = 8;

  /**
   * value of the named enumerated elev_001_00.
   */
  public static final int ASN_elev_001_00 = 9;

  /**
   * value of the named enumerated elev_000_50.
   */
  public static final int ASN_elev_000_50 = 10;

  /**
   * value of the named enumerated elev_000_20.
   */
  public static final int ASN_elev_000_20 = 11;

  /**
   * value of the named enumerated elev_000_10.
   */
  public static final int ASN_elev_000_10 = 12;

  /**
   * value of the named enumerated elev_000_05.
   */
  public static final int ASN_elev_000_05 = 13;

  /**
   * value of the named enumerated elev_000_02.
   */
  public static final int ASN_elev_000_02 = 14;

  /**
   * value of the named enumerated elev_000_01.
   */
  public static final int ASN_elev_000_01 = 15;

  /**
   *  Constructs a newly allocated ElevationConfidence.
   */
  public ElevationConfidence ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated ElevationConfidence that represents the primitive int argument.
   *  @param value the value to be represented by this ElevationConfidence.
   */
  public ElevationConfidence (int value)
  {
    super(value);
  };
}
