/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/EmergencyVehicleAlert.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the EmergencyVehicleAlert type of the dsrc module.
 */
public class EmergencyVehicleAlert extends fr.marben.asnsdk.japi.spe.ExtSequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 71;

  /**
   * optional field timeStamp.
   */
  public j2375.dsrc.asncode.dsrc.MinuteOfTheYear timeStamp;

  /**
   * optional field id.
   */
  public j2375.dsrc.asncode.dsrc.TemporaryID id;

  /**
   * mandatory field rsaMsg.
   */
  public j2375.dsrc.asncode.dsrc.RoadSideAlert rsaMsg;

  /**
   * <BR> the DSRCmsgID inside this 
   * <BR> data frame is set as per the 
   * <BR> RoadSideAlert  
   * optional field responseType.
   */
  public j2375.dsrc.asncode.dsrc.ResponseType responseType;

  /**
   * optional field details.
   */
  public j2375.dsrc.asncode.dsrc.EmergencyDetails details;

  /**
   * <BR> Combines these 3 items: 
   * <BR> SirenInUse,                     
   * <BR> LightbarInUse,                  
   * <BR> MultiVehicleReponse,
   * optional field mass.
   */
  public j2375.dsrc.asncode.dsrc.VehicleMass mass;

  /**
   * optional field basicType.
   */
  public j2375.dsrc.asncode.dsrc.VehicleType basicType;

  /**
   * <BR> gross size and axle cnt
   * <BR> type of vehicle and agency when known
   * optional field vehicleType.
   */
  public j2375.dsrc.asncode.itis.VehicleGroupAffected vehicleType;

  /**
   * optional field responseEquip.
   */
  public j2375.dsrc.asncode.itis.IncidentResponseEquipment responseEquip;

  /**
   * optional field responderType.
   */
  public j2375.dsrc.asncode.itis.ResponderGroupAffected responderType;

  /**
   * optional field regional.
   */
  public Regional regional;

  /**
   * class definition of the regional field.
   */
  public static class Regional extends fr.marben.asnsdk.japi.spe.SequenceOfValue
  {
    /**
     * class definition of the SEQUENCE field.
     */
    public static class SEQUENCE extends fr.marben.asnsdk.japi.spe.SequenceValue
    {
      /**
       * mandatory field regionId.
       */
      public j2375.dsrc.asncode.dsrc.RegionId regionId;

      /**
       * mandatory field regExtValue.
       */
      public fr.marben.asnsdk.japi.spe.OpenTypeValue regExtValue;

      /**
       *  Constructs a newly allocated SEQUENCE.
       */
      public SEQUENCE ()
      {
        super();
      };

      /**
       *  Gets the value of a component from this SEQUENCE.
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type identifier of the component.
       *  @return the value identified by the named type.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           return this.regionId;
         case 1 :
           return this.regExtValue;
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
         }
       }

      /**
       *  Creates a newly allocated component value from this SEQUENCE.
       *  this value is created for temporary use to solve atNotations
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type of this SEQUENCE.
       *  @return a value from a class implementing the IValue interface.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           return new j2375.dsrc.asncode.dsrc.RegionId();
         case 1 :
           return new fr.marben.asnsdk.japi.spe.OpenTypeValue();
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
         }
       }

      /**
       *  Creates and sets a newly allocated component value from this SEQUENCE.
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type of this SEQUENCE.
       *  @return a value from a class implementing the IValue interface.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           this.regionId = new j2375.dsrc.asncode.dsrc.RegionId();
           return this.regionId;
         case 1 :
           this.regExtValue = new fr.marben.asnsdk.japi.spe.OpenTypeValue();
           return this.regExtValue;
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
         }
       }

    }

    /**
     *  Constructs a newly allocated Regional.
     */
    public Regional ()
    {
      super();
    };

    /**
     *  Constructs a newly allocated Regional with the given list.
     *  @param list the list used to initialize this Regional.
     */
    public Regional (java.util.List list)
    {
      super(list);
    };
    
    /**
     *  Creates and appends a newly allocated component value from 
     *  this Regional.
     *  This method is only for ASNSDK internal use. 
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this Regional.
     *  @return a value from a class implementing de IValue interface.
     */
    public fr.marben.asnsdk.japi.vi.IValue asnAddNewSetSeqOfValue(
                          fr.marben.asnsdk.japi.Context context,
                          fr.marben.asnsdk.japi.vi.ISetSeqOfNamedType field)
    {
          j2375.dsrc.asncode.dsrc.EmergencyVehicleAlert.Regional.SEQUENCE value = new j2375.dsrc.asncode.dsrc.EmergencyVehicleAlert.Regional.SEQUENCE();
          this.valueList.add(value);
          return value;
    }
  }

  /**
   *  Constructs a newly allocated EmergencyVehicleAlert.
   */
  public EmergencyVehicleAlert ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this EmergencyVehicleAlert.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.timeStamp;
     case 1 :
       return this.id;
     case 2 :
       return this.rsaMsg;
     case 3 :
       return this.responseType;
     case 4 :
       return this.details;
     case 5 :
       return this.mass;
     case 6 :
       return this.basicType;
     case 7 :
       return this.vehicleType;
     case 8 :
       return this.responseEquip;
     case 9 :
       return this.responderType;
     case 10 :
       return this.regional;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this EmergencyVehicleAlert.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this EmergencyVehicleAlert.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.MinuteOfTheYear();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.TemporaryID();
     case 2 :
       return new j2375.dsrc.asncode.dsrc.RoadSideAlert();
     case 3 :
       return new j2375.dsrc.asncode.dsrc.ResponseType();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.EmergencyDetails();
     case 5 :
       return new j2375.dsrc.asncode.dsrc.VehicleMass();
     case 6 :
       return new j2375.dsrc.asncode.dsrc.VehicleType();
     case 7 :
       return new j2375.dsrc.asncode.itis.VehicleGroupAffected();
     case 8 :
       return new j2375.dsrc.asncode.itis.IncidentResponseEquipment();
     case 9 :
       return new j2375.dsrc.asncode.itis.ResponderGroupAffected();
     case 10 :
       return new Regional();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this EmergencyVehicleAlert.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this EmergencyVehicleAlert.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.timeStamp = new j2375.dsrc.asncode.dsrc.MinuteOfTheYear();
       return this.timeStamp;
     case 1 :
       this.id = new j2375.dsrc.asncode.dsrc.TemporaryID();
       return this.id;
     case 2 :
       this.rsaMsg = new j2375.dsrc.asncode.dsrc.RoadSideAlert();
       return this.rsaMsg;
     case 3 :
       this.responseType = new j2375.dsrc.asncode.dsrc.ResponseType();
       return this.responseType;
     case 4 :
       this.details = new j2375.dsrc.asncode.dsrc.EmergencyDetails();
       return this.details;
     case 5 :
       this.mass = new j2375.dsrc.asncode.dsrc.VehicleMass();
       return this.mass;
     case 6 :
       this.basicType = new j2375.dsrc.asncode.dsrc.VehicleType();
       return this.basicType;
     case 7 :
       this.vehicleType = new j2375.dsrc.asncode.itis.VehicleGroupAffected();
       return this.vehicleType;
     case 8 :
       this.responseEquip = new j2375.dsrc.asncode.itis.IncidentResponseEquipment();
       return this.responseEquip;
     case 9 :
       this.responderType = new j2375.dsrc.asncode.itis.ResponderGroupAffected();
       return this.responderType;
     case 10 :
       this.regional = new Regional();
       return this.regional;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets a group value from the EmergencyVehicleAlert.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Returns whether or not this group is present among the extensions.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @return <code>true</code>: when the group is present.
   *          <code>false</code>: when the group is not present.
   */
   public boolean asnIsSetSeqGroupPresent(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated group value of the EmergencyVehicleAlert.
   *  This group is created for temporary use, in order to solve atNotations.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated group value of the EmergencyVehicleAlert.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 71;
  }

}
