/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/HeadingSlice.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> LSB of 00125 degrees
 * <BR> A range of 0 to 3599875 degrees
 * Class definition of the HeadingSlice type of the dsrc module.
 */
public class HeadingSlice extends fr.marben.asnsdk.japi.spe.BitStringValue
{
  /**
   * value of the named bit from000_0to022_5degrees.
   */
  public static final int ASN_from000_0to022_5degrees = 0;

  /**
   * value of the named bit from022_5to045_0degrees.
   */
  public static final int ASN_from022_5to045_0degrees = 1;

  /**
   * value of the named bit from045_0to067_5degrees.
   */
  public static final int ASN_from045_0to067_5degrees = 2;

  /**
   * value of the named bit from067_5to090_0degrees.
   */
  public static final int ASN_from067_5to090_0degrees = 3;

  /**
   * value of the named bit from090_0to112_5degrees.
   */
  public static final int ASN_from090_0to112_5degrees = 4;

  /**
   * value of the named bit from112_5to135_0degrees.
   */
  public static final int ASN_from112_5to135_0degrees = 5;

  /**
   * value of the named bit from135_0to157_5degrees.
   */
  public static final int ASN_from135_0to157_5degrees = 6;

  /**
   * value of the named bit from157_5to180_0degrees.
   */
  public static final int ASN_from157_5to180_0degrees = 7;

  /**
   * value of the named bit from180_0to202_5degrees.
   */
  public static final int ASN_from180_0to202_5degrees = 8;

  /**
   * value of the named bit from202_5to225_0degrees.
   */
  public static final int ASN_from202_5to225_0degrees = 9;

  /**
   * value of the named bit from225_0to247_5degrees.
   */
  public static final int ASN_from225_0to247_5degrees = 10;

  /**
   * value of the named bit from247_5to270_0degrees.
   */
  public static final int ASN_from247_5to270_0degrees = 11;

  /**
   * value of the named bit from270_0to292_5degrees.
   */
  public static final int ASN_from270_0to292_5degrees = 12;

  /**
   * value of the named bit from292_5to315_0degrees.
   */
  public static final int ASN_from292_5to315_0degrees = 13;

  /**
   * value of the named bit from315_0to337_5degrees.
   */
  public static final int ASN_from315_0to337_5degrees = 14;

  /**
   * value of the named bit from337_5to360_0degrees.
   */
  public static final int ASN_from337_5to360_0degrees = 15;

  /**
   *  Constructs a newly allocated HeadingSlice.
   */
  public HeadingSlice ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated HeadingSlice.
   *  Sets the number of used bits using the int parameter
   *  and sets the internal value using the bytes array parameter.
   *  @param value the value to be represented by this HeadingSlice.
   *  @param bitCount the number of used bits to be represented by this HeadingSlice.
   *  @throws IllegalArgumentException if the bitCount is not consistent with the length of the value.
   */
  public HeadingSlice (byte[] value, int bitCount)
  {
    super(value, bitCount);
  }

  /**
   *  Constructs a newly allocated HeadingSlice.
   *  Sets the number of used bits using the int parameter
   *  and sets the internal value using the subarray of bytes.
   *  @param value the array containing the value to be represented by this HeadingSlice.
   *  @param bitOffset  the index of the first bit to be represented by this HeadingSlice.
   *  @param bitCount the number of used bits to be represented by this HeadingSlice.
   *  @throws IllegalArgumentException if the bitCount and bitOffset are not consistent with the length of the value.
   */
  public HeadingSlice (byte[] value, int bitOffset, int bitCount)
  {
    super(value, bitOffset, bitCount);
  }
}
