/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/Location_quality.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> LSB = 1/10 micro degree
 * <BR> Providing a range of plus-minus 180 degrees
 * Class definition of the Location_quality type of the dsrc module.
 */
public class Location_quality extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 138;

  /**
   * value of the named enumerated loc_qual_bt1m.
   */
  public static final int ASN_loc_qual_bt1m = 0;

  /**
   * value of the named enumerated loc_qual_bt5m.
   */
  public static final int ASN_loc_qual_bt5m = 1;

  /**
   * value of the named enumerated loc_qual_bt12m.
   */
  public static final int ASN_loc_qual_bt12m = 2;

  /**
   * value of the named enumerated loc_qual_bt50m.
   */
  public static final int ASN_loc_qual_bt50m = 3;

  /**
   * value of the named enumerated loc_qual_bt125m.
   */
  public static final int ASN_loc_qual_bt125m = 4;

  /**
   * value of the named enumerated loc_qual_bt500m.
   */
  public static final int ASN_loc_qual_bt500m = 5;

  /**
   * value of the named enumerated loc_qual_bt1250m.
   */
  public static final int ASN_loc_qual_bt1250m = 6;

  /**
   * value of the named enumerated loc_qual_unknown.
   */
  public static final int ASN_loc_qual_unknown = 7;

  /**
   *  Constructs a newly allocated Location_quality.
   */
  public Location_quality ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated Location_quality that represents the primitive int argument.
   *  @param value the value to be represented by this Location_quality.
   */
  public Location_quality (int value)
  {
    super(value);
  };
  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 138;
  }

}
