/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/ObstacleDistance.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the ObstacleDistance type of the dsrc module.
 */
public class ObstacleDistance extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated ObstacleDistance.
   */
  public ObstacleDistance ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated ObstacleDistance that represents the primitive int argument.
   *  @param value the value to be represented by this ObstacleDistance.
   */
  public ObstacleDistance (int value)
  {
    super(value);
  };
}
