/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/ObstacleDetection.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> Any optional Attributes which are needed
 * <BR> This includes changes to the current lane width and elevation
 * Class definition of the ObstacleDetection type of the dsrc module.
 */
public class ObstacleDetection extends fr.marben.asnsdk.japi.spe.ExtSequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 151;

  /**
   * mandatory field obDist.
   */
  public j2375.dsrc.asncode.dsrc.ObstacleDistance obDist;

  /**
   * <BR> Obstacle Distance        
   * mandatory field obDirect.
   */
  public j2375.dsrc.asncode.dsrc.ObstacleDirection obDirect;

  /**
   * <BR> Obstacle Direction
   * optional field description.
   */
  public j2375.dsrc.asncode.itis.ITIScodes description;

  /**
   * <BR> Uses a limited set of ITIS codes        
   * optional field locationDetails.
   */
  public j2375.dsrc.asncode.itis.GenericLocations locationDetails;

  /**
   * mandatory field dateTime.
   */
  public j2375.dsrc.asncode.dsrc.DDateTime dateTime;

  /**
   * <BR> Time detected
   * optional field vertEvent.
   */
  public j2375.dsrc.asncode.dsrc.VerticalAccelerationThreshold vertEvent;

  /**
   *  Constructs a newly allocated ObstacleDetection.
   */
  public ObstacleDetection ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this ObstacleDetection.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.obDist;
     case 1 :
       return this.obDirect;
     case 2 :
       return this.description;
     case 3 :
       return this.locationDetails;
     case 4 :
       return this.dateTime;
     case 5 :
       return this.vertEvent;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this ObstacleDetection.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this ObstacleDetection.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.ObstacleDistance();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.ObstacleDirection();
     case 2 :
       return new j2375.dsrc.asncode.itis.ITIScodes();
     case 3 :
       return new j2375.dsrc.asncode.itis.GenericLocations();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.DDateTime();
     case 5 :
       return new j2375.dsrc.asncode.dsrc.VerticalAccelerationThreshold();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this ObstacleDetection.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this ObstacleDetection.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.obDist = new j2375.dsrc.asncode.dsrc.ObstacleDistance();
       return this.obDist;
     case 1 :
       this.obDirect = new j2375.dsrc.asncode.dsrc.ObstacleDirection();
       return this.obDirect;
     case 2 :
       this.description = new j2375.dsrc.asncode.itis.ITIScodes();
       return this.description;
     case 3 :
       this.locationDetails = new j2375.dsrc.asncode.itis.GenericLocations();
       return this.locationDetails;
     case 4 :
       this.dateTime = new j2375.dsrc.asncode.dsrc.DDateTime();
       return this.dateTime;
     case 5 :
       this.vertEvent = new j2375.dsrc.asncode.dsrc.VerticalAccelerationThreshold();
       return this.vertEvent;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets a group value from the ObstacleDetection.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Returns whether or not this group is present among the extensions.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @return <code>true</code>: when the group is present.
   *          <code>false</code>: when the group is not present.
   */
   public boolean asnIsSetSeqGroupPresent(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated group value of the ObstacleDetection.
   *  This group is created for temporary use, in order to solve atNotations.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated group value of the ObstacleDetection.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 151;
  }

}
