/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/OffsetLL_B22.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> A range of +- 00131071 degrees
 * <BR> The value +131071 shall be used for values >= than +00131071 degrees
 * <BR> The value -131071 shall be used for values <= than -00131071 degrees
 * <BR> The value -131072 shall be used unknown
 * <BR> In LSB units of 01 microdegrees (unless a zoom is employed)
 * Class definition of the OffsetLL_B22 type of the dsrc module.
 */
public class OffsetLL_B22 extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated OffsetLL_B22.
   */
  public OffsetLL_B22 ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated OffsetLL_B22 that represents the primitive int argument.
   *  @param value the value to be represented by this OffsetLL_B22.
   */
  public OffsetLL_B22 (int value)
  {
    super(value);
  };
}
