/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/OffsetLL_B12.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> a range of +- 32768 meters
 * Class definition of the OffsetLL_B12 type of the dsrc module.
 */
public class OffsetLL_B12 extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated OffsetLL_B12.
   */
  public OffsetLL_B12 ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated OffsetLL_B12 that represents the primitive int argument.
   *  @param value the value to be represented by this OffsetLL_B12.
   */
  public OffsetLL_B12 (int value)
  {
    super(value);
  };
}
