/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/PathHistoryPoint.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the PathHistoryPoint type of the dsrc module.
 */
public class PathHistoryPoint extends fr.marben.asnsdk.japi.spe.ExtSequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 120;

  /**
   * mandatory field latOffset.
   */
  public j2375.dsrc.asncode.dsrc.OffsetLL_B18 latOffset;

  /**
   * mandatory field lonOffset.
   */
  public j2375.dsrc.asncode.dsrc.OffsetLL_B18 lonOffset;

  /**
   * mandatory field elevationOffset.
   */
  public j2375.dsrc.asncode.dsrc.VertOffset_B12 elevationOffset;

  /**
   * mandatory field timeOffset.
   */
  public j2375.dsrc.asncode.dsrc.TimeOffset timeOffset;

  /**
   * <BR> Offset backwards in time 
   * optional field speed.
   */
  public j2375.dsrc.asncode.dsrc.Speed speed;

  /**
   * <BR> Speed over the reported period
   * optional field posAccuracy.
   */
  public j2375.dsrc.asncode.dsrc.PositionalAccuracy posAccuracy;

  /**
   * <BR> The accuracy of this value
   * optional field heading.
   */
  public j2375.dsrc.asncode.dsrc.CoarseHeading heading;

  /**
   *  Constructs a newly allocated PathHistoryPoint.
   */
  public PathHistoryPoint ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this PathHistoryPoint.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.latOffset;
     case 1 :
       return this.lonOffset;
     case 2 :
       return this.elevationOffset;
     case 3 :
       return this.timeOffset;
     case 4 :
       return this.speed;
     case 5 :
       return this.posAccuracy;
     case 6 :
       return this.heading;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this PathHistoryPoint.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this PathHistoryPoint.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.OffsetLL_B18();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.OffsetLL_B18();
     case 2 :
       return new j2375.dsrc.asncode.dsrc.VertOffset_B12();
     case 3 :
       return new j2375.dsrc.asncode.dsrc.TimeOffset();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.Speed();
     case 5 :
       return new j2375.dsrc.asncode.dsrc.PositionalAccuracy();
     case 6 :
       return new j2375.dsrc.asncode.dsrc.CoarseHeading();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this PathHistoryPoint.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this PathHistoryPoint.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.latOffset = new j2375.dsrc.asncode.dsrc.OffsetLL_B18();
       return this.latOffset;
     case 1 :
       this.lonOffset = new j2375.dsrc.asncode.dsrc.OffsetLL_B18();
       return this.lonOffset;
     case 2 :
       this.elevationOffset = new j2375.dsrc.asncode.dsrc.VertOffset_B12();
       return this.elevationOffset;
     case 3 :
       this.timeOffset = new j2375.dsrc.asncode.dsrc.TimeOffset();
       return this.timeOffset;
     case 4 :
       this.speed = new j2375.dsrc.asncode.dsrc.Speed();
       return this.speed;
     case 5 :
       this.posAccuracy = new j2375.dsrc.asncode.dsrc.PositionalAccuracy();
       return this.posAccuracy;
     case 6 :
       this.heading = new j2375.dsrc.asncode.dsrc.CoarseHeading();
       return this.heading;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets a group value from the PathHistoryPoint.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Returns whether or not this group is present among the extensions.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @return <code>true</code>: when the group is present.
   *          <code>false</code>: when the group is not present.
   */
   public boolean asnIsSetSeqGroupPresent(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated group value of the PathHistoryPoint.
   *  This group is created for temporary use, in order to solve atNotations.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated group value of the PathHistoryPoint.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 120;
  }

}
