/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/PayloadData.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> A range of +- 08388607 degrees
 * <BR> In LSB units of 01 microdegrees (unless a zoom is employed)
 * Class definition of the PayloadData type of the dsrc module.
 */
public class PayloadData extends fr.marben.asnsdk.japi.spe.OctetStringValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 152;

  /**
   *  Constructs a newly allocated PayloadData.
   */
  public PayloadData ()
  {
    super();
  };

  /**
   * Constructor of the PayloadData.
   */
  public PayloadData (byte[] value)
  {
    super(value);
  }
  /**
   *  Constructs a newly allocated PayloadData from a subarray of bytes.
   *  @param value the byte array used to initialize this OctetStringValue
   *  @param offset the index of the first byte to store in this OctetStringValue
   *  @param count the number of bytes to store in this OctetStringValue
   */
  public PayloadData (byte[] value, int offset, int count)
  {
    super(value, offset, count);
  }
  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 152;
  }

}
