/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/PersonalSafetyMessage.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the PersonalSafetyMessage type of the dsrc module.
 */
public class PersonalSafetyMessage extends fr.marben.asnsdk.japi.spe.ExtSequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 153;

  /**
   * mandatory field basicType.
   */
  public j2375.dsrc.asncode.dsrc.PersonalDeviceUserType basicType;

  /**
   * mandatory field secMark.
   */
  public j2375.dsrc.asncode.dsrc.DSecond secMark;

  /**
   * mandatory field msgCnt.
   */
  public j2375.dsrc.asncode.dsrc.MsgCount msgCnt;

  /**
   * mandatory field id.
   */
  public j2375.dsrc.asncode.dsrc.TemporaryID id;

  /**
   * mandatory field position.
   */
  public j2375.dsrc.asncode.dsrc.Position3D position;

  /**
   * <BR>  Lat, Long, Elevation     
   * mandatory field accuracy.
   */
  public j2375.dsrc.asncode.dsrc.PositionalAccuracy accuracy;

  /**
   * mandatory field speed.
   */
  public j2375.dsrc.asncode.dsrc.Velocity speed;

  /**
   * mandatory field heading.
   */
  public j2375.dsrc.asncode.dsrc.Heading heading;

  /**
   * optional field accelSet.
   */
  public j2375.dsrc.asncode.dsrc.AccelerationSet4Way accelSet;

  /**
   * optional field pathHistory.
   */
  public j2375.dsrc.asncode.dsrc.PathHistory pathHistory;

  /**
   * optional field pathPrediction.
   */
  public j2375.dsrc.asncode.dsrc.PathPrediction pathPrediction;

  /**
   * optional field propulsion.
   */
  public j2375.dsrc.asncode.dsrc.PropelledInformation propulsion;

  /**
   * optional field useState.
   */
  public j2375.dsrc.asncode.dsrc.PersonalDeviceUsageState useState;

  /**
   * optional field crossRequest.
   */
  public j2375.dsrc.asncode.dsrc.PersonalCrossingRequest crossRequest;

  /**
   * optional field crossState.
   */
  public j2375.dsrc.asncode.dsrc.PersonalCrossingInProgress crossState;

  /**
   * optional field clusterSize.
   */
  public j2375.dsrc.asncode.dsrc.NumberOfParticipantsInCluster clusterSize;

  /**
   * optional field clusterRadius.
   */
  public j2375.dsrc.asncode.dsrc.PersonalClusterRadius clusterRadius;

  /**
   * optional field eventResponderType.
   */
  public j2375.dsrc.asncode.dsrc.PublicSafetyEventResponderWorkerType eventResponderType;

  /**
   * optional field activityType.
   */
  public j2375.dsrc.asncode.dsrc.PublicSafetyAndRoadWorkerActivity activityType;

  /**
   * optional field activitySubType.
   */
  public j2375.dsrc.asncode.dsrc.PublicSafetyDirectingTrafficSubType activitySubType;

  /**
   * optional field assistType.
   */
  public j2375.dsrc.asncode.dsrc.PersonalAssistive assistType;

  /**
   * optional field sizing.
   */
  public j2375.dsrc.asncode.dsrc.UserSizeAndBehaviour sizing;

  /**
   * optional field attachment.
   */
  public j2375.dsrc.asncode.dsrc.Attachment attachment;

  /**
   * optional field attachmentRadius.
   */
  public j2375.dsrc.asncode.dsrc.AttachmentRadius attachmentRadius;

  /**
   * optional field animalType.
   */
  public j2375.dsrc.asncode.dsrc.AnimalType animalType;

  /**
   * optional field regional.
   */
  public Regional regional;

  /**
   * class definition of the regional field.
   */
  public static class Regional extends fr.marben.asnsdk.japi.spe.SequenceOfValue
  {
    /**
     * class definition of the SEQUENCE field.
     */
    public static class SEQUENCE extends fr.marben.asnsdk.japi.spe.SequenceValue
    {
      /**
       * mandatory field regionId.
       */
      public j2375.dsrc.asncode.dsrc.RegionId regionId;

      /**
       * mandatory field regExtValue.
       */
      public fr.marben.asnsdk.japi.spe.OpenTypeValue regExtValue;

      /**
       *  Constructs a newly allocated SEQUENCE.
       */
      public SEQUENCE ()
      {
        super();
      };

      /**
       *  Gets the value of a component from this SEQUENCE.
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type identifier of the component.
       *  @return the value identified by the named type.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           return this.regionId;
         case 1 :
           return this.regExtValue;
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
         }
       }

      /**
       *  Creates a newly allocated component value from this SEQUENCE.
       *  this value is created for temporary use to solve atNotations
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type of this SEQUENCE.
       *  @return a value from a class implementing the IValue interface.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           return new j2375.dsrc.asncode.dsrc.RegionId();
         case 1 :
           return new fr.marben.asnsdk.japi.spe.OpenTypeValue();
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
         }
       }

      /**
       *  Creates and sets a newly allocated component value from this SEQUENCE.
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type of this SEQUENCE.
       *  @return a value from a class implementing the IValue interface.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
       {
         switch (field.getFieldNumber(context))
         {
         case 0 :
           this.regionId = new j2375.dsrc.asncode.dsrc.RegionId();
           return this.regionId;
         case 1 :
           this.regExtValue = new fr.marben.asnsdk.japi.spe.OpenTypeValue();
           return this.regExtValue;
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
         }
       }

    }

    /**
     *  Constructs a newly allocated Regional.
     */
    public Regional ()
    {
      super();
    };

    /**
     *  Constructs a newly allocated Regional with the given list.
     *  @param list the list used to initialize this Regional.
     */
    public Regional (java.util.List list)
    {
      super(list);
    };
    
    /**
     *  Creates and appends a newly allocated component value from 
     *  this Regional.
     *  This method is only for ASNSDK internal use. 
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this Regional.
     *  @return a value from a class implementing de IValue interface.
     */
    public fr.marben.asnsdk.japi.vi.IValue asnAddNewSetSeqOfValue(
                          fr.marben.asnsdk.japi.Context context,
                          fr.marben.asnsdk.japi.vi.ISetSeqOfNamedType field)
    {
          j2375.dsrc.asncode.dsrc.PersonalSafetyMessage.Regional.SEQUENCE value = new j2375.dsrc.asncode.dsrc.PersonalSafetyMessage.Regional.SEQUENCE();
          this.valueList.add(value);
          return value;
    }
  }

  /**
   *  Constructs a newly allocated PersonalSafetyMessage.
   */
  public PersonalSafetyMessage ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this PersonalSafetyMessage.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.basicType;
     case 1 :
       return this.secMark;
     case 2 :
       return this.msgCnt;
     case 3 :
       return this.id;
     case 4 :
       return this.position;
     case 5 :
       return this.accuracy;
     case 6 :
       return this.speed;
     case 7 :
       return this.heading;
     case 8 :
       return this.accelSet;
     case 9 :
       return this.pathHistory;
     case 10 :
       return this.pathPrediction;
     case 11 :
       return this.propulsion;
     case 12 :
       return this.useState;
     case 13 :
       return this.crossRequest;
     case 14 :
       return this.crossState;
     case 15 :
       return this.clusterSize;
     case 16 :
       return this.clusterRadius;
     case 17 :
       return this.eventResponderType;
     case 18 :
       return this.activityType;
     case 19 :
       return this.activitySubType;
     case 20 :
       return this.assistType;
     case 21 :
       return this.sizing;
     case 22 :
       return this.attachment;
     case 23 :
       return this.attachmentRadius;
     case 24 :
       return this.animalType;
     case 25 :
       return this.regional;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this PersonalSafetyMessage.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this PersonalSafetyMessage.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.PersonalDeviceUserType();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.DSecond();
     case 2 :
       return new j2375.dsrc.asncode.dsrc.MsgCount();
     case 3 :
       return new j2375.dsrc.asncode.dsrc.TemporaryID();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.Position3D();
     case 5 :
       return new j2375.dsrc.asncode.dsrc.PositionalAccuracy();
     case 6 :
       return new j2375.dsrc.asncode.dsrc.Velocity();
     case 7 :
       return new j2375.dsrc.asncode.dsrc.Heading();
     case 8 :
       return new j2375.dsrc.asncode.dsrc.AccelerationSet4Way();
     case 9 :
       return new j2375.dsrc.asncode.dsrc.PathHistory();
     case 10 :
       return new j2375.dsrc.asncode.dsrc.PathPrediction();
     case 11 :
       return new j2375.dsrc.asncode.dsrc.PropelledInformation();
     case 12 :
       return new j2375.dsrc.asncode.dsrc.PersonalDeviceUsageState();
     case 13 :
       return new j2375.dsrc.asncode.dsrc.PersonalCrossingRequest();
     case 14 :
       return new j2375.dsrc.asncode.dsrc.PersonalCrossingInProgress();
     case 15 :
       return new j2375.dsrc.asncode.dsrc.NumberOfParticipantsInCluster();
     case 16 :
       return new j2375.dsrc.asncode.dsrc.PersonalClusterRadius();
     case 17 :
       return new j2375.dsrc.asncode.dsrc.PublicSafetyEventResponderWorkerType();
     case 18 :
       return new j2375.dsrc.asncode.dsrc.PublicSafetyAndRoadWorkerActivity();
     case 19 :
       return new j2375.dsrc.asncode.dsrc.PublicSafetyDirectingTrafficSubType();
     case 20 :
       return new j2375.dsrc.asncode.dsrc.PersonalAssistive();
     case 21 :
       return new j2375.dsrc.asncode.dsrc.UserSizeAndBehaviour();
     case 22 :
       return new j2375.dsrc.asncode.dsrc.Attachment();
     case 23 :
       return new j2375.dsrc.asncode.dsrc.AttachmentRadius();
     case 24 :
       return new j2375.dsrc.asncode.dsrc.AnimalType();
     case 25 :
       return new Regional();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this PersonalSafetyMessage.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this PersonalSafetyMessage.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.basicType = new j2375.dsrc.asncode.dsrc.PersonalDeviceUserType();
       return this.basicType;
     case 1 :
       this.secMark = new j2375.dsrc.asncode.dsrc.DSecond();
       return this.secMark;
     case 2 :
       this.msgCnt = new j2375.dsrc.asncode.dsrc.MsgCount();
       return this.msgCnt;
     case 3 :
       this.id = new j2375.dsrc.asncode.dsrc.TemporaryID();
       return this.id;
     case 4 :
       this.position = new j2375.dsrc.asncode.dsrc.Position3D();
       return this.position;
     case 5 :
       this.accuracy = new j2375.dsrc.asncode.dsrc.PositionalAccuracy();
       return this.accuracy;
     case 6 :
       this.speed = new j2375.dsrc.asncode.dsrc.Velocity();
       return this.speed;
     case 7 :
       this.heading = new j2375.dsrc.asncode.dsrc.Heading();
       return this.heading;
     case 8 :
       this.accelSet = new j2375.dsrc.asncode.dsrc.AccelerationSet4Way();
       return this.accelSet;
     case 9 :
       this.pathHistory = new j2375.dsrc.asncode.dsrc.PathHistory();
       return this.pathHistory;
     case 10 :
       this.pathPrediction = new j2375.dsrc.asncode.dsrc.PathPrediction();
       return this.pathPrediction;
     case 11 :
       this.propulsion = new j2375.dsrc.asncode.dsrc.PropelledInformation();
       return this.propulsion;
     case 12 :
       this.useState = new j2375.dsrc.asncode.dsrc.PersonalDeviceUsageState();
       return this.useState;
     case 13 :
       this.crossRequest = new j2375.dsrc.asncode.dsrc.PersonalCrossingRequest();
       return this.crossRequest;
     case 14 :
       this.crossState = new j2375.dsrc.asncode.dsrc.PersonalCrossingInProgress();
       return this.crossState;
     case 15 :
       this.clusterSize = new j2375.dsrc.asncode.dsrc.NumberOfParticipantsInCluster();
       return this.clusterSize;
     case 16 :
       this.clusterRadius = new j2375.dsrc.asncode.dsrc.PersonalClusterRadius();
       return this.clusterRadius;
     case 17 :
       this.eventResponderType = new j2375.dsrc.asncode.dsrc.PublicSafetyEventResponderWorkerType();
       return this.eventResponderType;
     case 18 :
       this.activityType = new j2375.dsrc.asncode.dsrc.PublicSafetyAndRoadWorkerActivity();
       return this.activityType;
     case 19 :
       this.activitySubType = new j2375.dsrc.asncode.dsrc.PublicSafetyDirectingTrafficSubType();
       return this.activitySubType;
     case 20 :
       this.assistType = new j2375.dsrc.asncode.dsrc.PersonalAssistive();
       return this.assistType;
     case 21 :
       this.sizing = new j2375.dsrc.asncode.dsrc.UserSizeAndBehaviour();
       return this.sizing;
     case 22 :
       this.attachment = new j2375.dsrc.asncode.dsrc.Attachment();
       return this.attachment;
     case 23 :
       this.attachmentRadius = new j2375.dsrc.asncode.dsrc.AttachmentRadius();
       return this.attachmentRadius;
     case 24 :
       this.animalType = new j2375.dsrc.asncode.dsrc.AnimalType();
       return this.animalType;
     case 25 :
       this.regional = new Regional();
       return this.regional;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets a group value from the PersonalSafetyMessage.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Returns whether or not this group is present among the extensions.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @return <code>true</code>: when the group is present.
   *          <code>false</code>: when the group is not present.
   */
   public boolean asnIsSetSeqGroupPresent(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated group value of the PersonalSafetyMessage.
   *  This group is created for temporary use, in order to solve atNotations.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated group value of the PersonalSafetyMessage.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 153;
  }

}
