/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/PositionConfidence.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the PositionConfidence type of the dsrc module.
 */
public class PositionConfidence extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated unavailable.
   */
  public static final int ASN_unavailable = 0;

  /**
   * value of the named enumerated a500m.
   */
  public static final int ASN_a500m = 1;

  /**
   * value of the named enumerated a200m.
   */
  public static final int ASN_a200m = 2;

  /**
   * value of the named enumerated a100m.
   */
  public static final int ASN_a100m = 3;

  /**
   * value of the named enumerated a50m.
   */
  public static final int ASN_a50m = 4;

  /**
   * value of the named enumerated a20m.
   */
  public static final int ASN_a20m = 5;

  /**
   * value of the named enumerated a10m.
   */
  public static final int ASN_a10m = 6;

  /**
   * value of the named enumerated a5m.
   */
  public static final int ASN_a5m = 7;

  /**
   * value of the named enumerated a2m.
   */
  public static final int ASN_a2m = 8;

  /**
   * value of the named enumerated a1m.
   */
  public static final int ASN_a1m = 9;

  /**
   * value of the named enumerated a50cm.
   */
  public static final int ASN_a50cm = 10;

  /**
   * value of the named enumerated a20cm.
   */
  public static final int ASN_a20cm = 11;

  /**
   * value of the named enumerated a10cm.
   */
  public static final int ASN_a10cm = 12;

  /**
   * value of the named enumerated a5cm.
   */
  public static final int ASN_a5cm = 13;

  /**
   * value of the named enumerated a2cm.
   */
  public static final int ASN_a2cm = 14;

  /**
   * value of the named enumerated a1cm.
   */
  public static final int ASN_a1cm = 15;

  /**
   *  Constructs a newly allocated PositionConfidence.
   */
  public PositionConfidence ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated PositionConfidence that represents the primitive int argument.
   *  @param value the value to be represented by this PositionConfidence.
   */
  public PositionConfidence (int value)
  {
    super(value);
  };
}
