/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/RainSensor.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> with the LSB unit value determined elsewhere
 * <BR> the value 4095 shall be used for unknown
 * Class definition of the RainSensor type of the dsrc module.
 */
public class RainSensor extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated none.
   */
  public static final int ASN_none = 0;

  /**
   * value of the named enumerated lightMist.
   */
  public static final int ASN_lightMist = 1;

  /**
   * value of the named enumerated heavyMist.
   */
  public static final int ASN_heavyMist = 2;

  /**
   * value of the named enumerated lightRainOrDrizzle.
   */
  public static final int ASN_lightRainOrDrizzle = 3;

  /**
   * value of the named enumerated rain.
   */
  public static final int ASN_rain = 4;

  /**
   * value of the named enumerated moderateRain.
   */
  public static final int ASN_moderateRain = 5;

  /**
   * value of the named enumerated heavyRain.
   */
  public static final int ASN_heavyRain = 6;

  /**
   * value of the named enumerated heavyDownpour.
   */
  public static final int ASN_heavyDownpour = 7;

  /**
   *  Constructs a newly allocated RainSensor.
   */
  public RainSensor ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated RainSensor that represents the primitive int argument.
   *  @param value the value to be represented by this RainSensor.
   */
  public RainSensor (int value)
  {
    super(value);
  };
}
