/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/RequestSubRole.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the RequestSubRole type of the dsrc module.
 */
public class RequestSubRole extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated requestSubRoleUnKnown.
   */
  public static final int ASN_requestSubRoleUnKnown = 0;

  /**
   * value of the named enumerated requestSubRole1.
   */
  public static final int ASN_requestSubRole1 = 1;

  /**
   * value of the named enumerated requestSubRole2.
   */
  public static final int ASN_requestSubRole2 = 2;

  /**
   * value of the named enumerated requestSubRole3.
   */
  public static final int ASN_requestSubRole3 = 3;

  /**
   * value of the named enumerated requestSubRole4.
   */
  public static final int ASN_requestSubRole4 = 4;

  /**
   * value of the named enumerated requestSubRole5.
   */
  public static final int ASN_requestSubRole5 = 5;

  /**
   * value of the named enumerated requestSubRole6.
   */
  public static final int ASN_requestSubRole6 = 6;

  /**
   * value of the named enumerated requestSubRole7.
   */
  public static final int ASN_requestSubRole7 = 7;

  /**
   * value of the named enumerated requestSubRole8.
   */
  public static final int ASN_requestSubRole8 = 8;

  /**
   * value of the named enumerated requestSubRole9.
   */
  public static final int ASN_requestSubRole9 = 9;

  /**
   * value of the named enumerated requestSubRole10.
   */
  public static final int ASN_requestSubRole10 = 10;

  /**
   * value of the named enumerated requestSubRole11.
   */
  public static final int ASN_requestSubRole11 = 11;

  /**
   * value of the named enumerated requestSubRole12.
   */
  public static final int ASN_requestSubRole12 = 12;

  /**
   * value of the named enumerated requestSubRole13.
   */
  public static final int ASN_requestSubRole13 = 13;

  /**
   * value of the named enumerated requestSubRole14.
   */
  public static final int ASN_requestSubRole14 = 14;

  /**
   * value of the named enumerated requestSubRoleReserved.
   */
  public static final int ASN_requestSubRoleReserved = 15;

  /**
   *  Constructs a newly allocated RequestSubRole.
   */
  public RequestSubRole ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated RequestSubRole that represents the primitive int argument.
   *  @param value the value to be represented by this RequestSubRole.
   */
  public RequestSubRole (int value)
  {
    super(value);
  };
}
