/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/RestrictionAppliesTo.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the RestrictionAppliesTo type of the dsrc module.
 */
public class RestrictionAppliesTo extends fr.marben.asnsdk.japi.spe.ExtEnumeratedValue
{
  /**
   * value of the named enumerated none.
   */
  public static final int ASN_none = 0;

  /**
   * value of the named enumerated equippedTransit.
   */
  public static final int ASN_equippedTransit = 1;

  /**
   * value of the named enumerated equippedTaxis.
   */
  public static final int ASN_equippedTaxis = 2;

  /**
   * value of the named enumerated equippedOther.
   */
  public static final int ASN_equippedOther = 3;

  /**
   * value of the named enumerated emissionCompliant.
   */
  public static final int ASN_emissionCompliant = 4;

  /**
   * value of the named enumerated equippedBicycle.
   */
  public static final int ASN_equippedBicycle = 5;

  /**
   * value of the named enumerated weightCompliant.
   */
  public static final int ASN_weightCompliant = 6;

  /**
   * value of the named enumerated heightCompliant.
   */
  public static final int ASN_heightCompliant = 7;

  /**
   * value of the named enumerated pedestrians.
   */
  public static final int ASN_pedestrians = 8;

  /**
   * value of the named enumerated slowMovingPersons.
   */
  public static final int ASN_slowMovingPersons = 9;

  /**
   * value of the named enumerated wheelchairUsers.
   */
  public static final int ASN_wheelchairUsers = 10;

  /**
   * value of the named enumerated visualDisabilities.
   */
  public static final int ASN_visualDisabilities = 11;

  /**
   * value of the named enumerated audioDisabilities.
   */
  public static final int ASN_audioDisabilities = 12;

  /**
   * value of the named enumerated otherUnknownDisabilities.
   */
  public static final int ASN_otherUnknownDisabilities = 13;

  /**
   *  Constructs a newly allocated RestrictionAppliesTo.
   */
  public RestrictionAppliesTo ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated RestrictionAppliesTo that represents the primitive int argument.
   *  @param value the value to be represented by this RestrictionAppliesTo.
   */
  public RestrictionAppliesTo (int value)
  {
    super(value);
  };

  /**
   *  Constructs a newly allocated RestrictionAppliesTo that represents the unknownExt argument.
   *  @param unknownExt the unknown extension value to be represented by this RestrictionAppliesTo.
   */
  public RestrictionAppliesTo (fr.marben.asnsdk.japi.UnknownExtensionValue unknownExt)
  {
    super(unknownExt);
  };
}
