/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/SpeedandHeadingandThrottleConfidence.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> HAZMAT and Cargo details to be added in a future revision
 * <BR> Wideload, oversized load to be added in a future revision
 * Class definition of the SpeedandHeadingandThrottleConfidence type of the dsrc module.
 */
public class SpeedandHeadingandThrottleConfidence extends fr.marben.asnsdk.japi.spe.SequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 52;

  /**
   * mandatory field heading.
   */
  public j2375.dsrc.asncode.dsrc.HeadingConfidence heading;

  /**
   * mandatory field speed.
   */
  public j2375.dsrc.asncode.dsrc.SpeedConfidence speed;

  /**
   * mandatory field throttle.
   */
  public j2375.dsrc.asncode.dsrc.ThrottleConfidence throttle;

  /**
   *  Constructs a newly allocated SpeedandHeadingandThrottleConfidence.
   */
  public SpeedandHeadingandThrottleConfidence ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this SpeedandHeadingandThrottleConfidence.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.heading;
     case 1 :
       return this.speed;
     case 2 :
       return this.throttle;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this SpeedandHeadingandThrottleConfidence.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this SpeedandHeadingandThrottleConfidence.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.HeadingConfidence();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.SpeedConfidence();
     case 2 :
       return new j2375.dsrc.asncode.dsrc.ThrottleConfidence();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this SpeedandHeadingandThrottleConfidence.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this SpeedandHeadingandThrottleConfidence.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.heading = new j2375.dsrc.asncode.dsrc.HeadingConfidence();
       return this.heading;
     case 1 :
       this.speed = new j2375.dsrc.asncode.dsrc.SpeedConfidence();
       return this.speed;
     case 2 :
       this.throttle = new j2375.dsrc.asncode.dsrc.ThrottleConfidence();
       return this.throttle;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 52;
  }

}
