/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/ThrottleConfidence.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> units of sec
 * Class definition of the ThrottleConfidence type of the dsrc module.
 */
public class ThrottleConfidence extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated unavailable.
   */
  public static final int ASN_unavailable = 0;

  /**
   * value of the named enumerated prec10percent.
   */
  public static final int ASN_prec10percent = 1;

  /**
   * value of the named enumerated prec1percent.
   */
  public static final int ASN_prec1percent = 2;

  /**
   * value of the named enumerated prec0_5percent.
   */
  public static final int ASN_prec0_5percent = 3;

  /**
   *  Constructs a newly allocated ThrottleConfidence.
   */
  public ThrottleConfidence ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated ThrottleConfidence that represents the primitive int argument.
   *  @param value the value to be represented by this ThrottleConfidence.
   */
  public ThrottleConfidence (int value)
  {
    super(value);
  };
}
