/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/TransitVehicleOccupancy.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the TransitVehicleOccupancy type of the dsrc module.
 */
public class TransitVehicleOccupancy extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated occupancyUnknown.
   */
  public static final int ASN_occupancyUnknown = 0;

  /**
   * value of the named enumerated occupancyEmpty.
   */
  public static final int ASN_occupancyEmpty = 1;

  /**
   * value of the named enumerated occupancyVeryLow.
   */
  public static final int ASN_occupancyVeryLow = 2;

  /**
   * value of the named enumerated occupancyLow.
   */
  public static final int ASN_occupancyLow = 3;

  /**
   * value of the named enumerated occupancyMed.
   */
  public static final int ASN_occupancyMed = 4;

  /**
   * value of the named enumerated occupancyHigh.
   */
  public static final int ASN_occupancyHigh = 5;

  /**
   * value of the named enumerated occupancyNearlyFull.
   */
  public static final int ASN_occupancyNearlyFull = 6;

  /**
   * value of the named enumerated occupancyFull.
   */
  public static final int ASN_occupancyFull = 7;

  /**
   *  Constructs a newly allocated TransitVehicleOccupancy.
   */
  public TransitVehicleOccupancy ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated TransitVehicleOccupancy that represents the primitive int argument.
   *  @param value the value to be represented by this TransitVehicleOccupancy.
   */
  public TransitVehicleOccupancy (int value)
  {
    super(value);
  };
}
