/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/VehicleType.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the VehicleType type of the dsrc module.
 */
public class VehicleType extends fr.marben.asnsdk.japi.spe.ExtEnumeratedValue
{
  /**
   * value of the named enumerated none.
   */
  public static final int ASN_none = 0;

  /**
   * value of the named enumerated unknown.
   */
  public static final int ASN_unknown = 1;

  /**
   * value of the named enumerated special.
   */
  public static final int ASN_special = 2;

  /**
   * value of the named enumerated moto.
   */
  public static final int ASN_moto = 3;

  /**
   * value of the named enumerated car.
   */
  public static final int ASN_car = 4;

  /**
   * value of the named enumerated carOther.
   */
  public static final int ASN_carOther = 5;

  /**
   * value of the named enumerated bus.
   */
  public static final int ASN_bus = 6;

  /**
   * value of the named enumerated axleCnt2.
   */
  public static final int ASN_axleCnt2 = 7;

  /**
   * value of the named enumerated axleCnt3.
   */
  public static final int ASN_axleCnt3 = 8;

  /**
   * value of the named enumerated axleCnt4.
   */
  public static final int ASN_axleCnt4 = 9;

  /**
   * value of the named enumerated axleCnt4Trailer.
   */
  public static final int ASN_axleCnt4Trailer = 10;

  /**
   * value of the named enumerated axleCnt5Trailer.
   */
  public static final int ASN_axleCnt5Trailer = 11;

  /**
   * value of the named enumerated axleCnt6Trailer.
   */
  public static final int ASN_axleCnt6Trailer = 12;

  /**
   * value of the named enumerated axleCnt5MultiTrailer.
   */
  public static final int ASN_axleCnt5MultiTrailer = 13;

  /**
   * value of the named enumerated axleCnt6MultiTrailer.
   */
  public static final int ASN_axleCnt6MultiTrailer = 14;

  /**
   * value of the named enumerated axleCnt7MultiTrailer.
   */
  public static final int ASN_axleCnt7MultiTrailer = 15;

  /**
   *  Constructs a newly allocated VehicleType.
   */
  public VehicleType ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated VehicleType that represents the primitive int argument.
   *  @param value the value to be represented by this VehicleType.
   */
  public VehicleType (int value)
  {
    super(value);
  };

  /**
   *  Constructs a newly allocated VehicleType that represents the unknownExt argument.
   *  @param unknownExt the unknown extension value to be represented by this VehicleType.
   */
  public VehicleType (fr.marben.asnsdk.japi.UnknownExtensionValue unknownExt)
  {
    super(unknownExt);
  };
}
