/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/VehicleIdent.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the VehicleIdent type of the dsrc module.
 */
public class VehicleIdent extends fr.marben.asnsdk.japi.spe.ExtSequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 163;

  /**
   * optional field name.
   */
  public j2375.dsrc.asncode.dsrc.DescriptiveName name;

  /**
   * <BR> a human readable name for debugging use
   * optional field vin.
   */
  public j2375.dsrc.asncode.dsrc.VINstring vin;

  /**
   * <BR> vehicle VIN value
   * optional field ownerCode.
   */
  public fr.marben.asnsdk.japi.spe.IA5StringValue ownerCode;

  /**
   * <BR> vehicle owner code 
   * optional field id.
   */
  public j2375.dsrc.asncode.dsrc.VehicleID id;

  /**
   * <BR> same value used in the BSM
   * optional field vehicleType.
   */
  public j2375.dsrc.asncode.dsrc.VehicleType vehicleType;

  /**
   * optional field vehicleClass.
   */
  public VehicleClass vehicleClass;

  /**
   * class definition of the vehicleClass field.
   */
  public static class VehicleClass extends fr.marben.asnsdk.japi.spe.ChoiceValue
  {
    /**
     * value of the fieldNumber for the field vGroup.
     * <BR>Use {@link j2375.dsrc.asncode.itis.VehicleGroupAffected j2375.dsrc.asncode.itis.VehicleGroupAffected} for the values of this type.
     */
    public static final short ASN_vGroup = 0;

    /**
     * value of the fieldNumber for the field rGroup.
     * <BR>Use {@link j2375.dsrc.asncode.itis.ResponderGroupAffected j2375.dsrc.asncode.itis.ResponderGroupAffected} for the values of this type.
     */
    public static final short ASN_rGroup = 1;

    /**
     * value of the fieldNumber for the field rEquip.
     * <BR>Use {@link j2375.dsrc.asncode.itis.IncidentResponseEquipment j2375.dsrc.asncode.itis.IncidentResponseEquipment} for the values of this type.
     */
    public static final short ASN_rEquip = 2;

    /**
     *  Constructs a newly allocated VehicleClass.
     */
    public VehicleClass ()
    {
      super();
    };

    /**
     *  Create a newly allocated VehicleClass.
     *  @param fieldNumber the named type identifier of the component.
     *  @param value the value to set.
     *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
     */
     public VehicleClass(short fieldNumber,
                          fr.marben.asnsdk.japi.spe.Value value)
                          throws fr.marben.asnsdk.japi.InvalidStructureException
     {
       this.fieldNumber = fieldNumber;
       switch (fieldNumber)
       {
       case 0 :
         this.value = (j2375.dsrc.asncode.itis.VehicleGroupAffected)value;
         break;
       case 1 :
         this.value = (j2375.dsrc.asncode.itis.ResponderGroupAffected)value;
         break;
       case 2 :
         this.value = (j2375.dsrc.asncode.itis.IncidentResponseEquipment)value;
         break;
       default :
         throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
       }
     }

    /**
     *  Sets the value of a component from this VehicleClass.
     *  @param fieldNumber the named type identifier of the component.
     *  @param value the value to set.
     *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
     */
     public void setValue(short fieldNumber,
                          fr.marben.asnsdk.japi.spe.Value value)
                          throws fr.marben.asnsdk.japi.InvalidStructureException
     {
       this.fieldNumber = fieldNumber;
       switch (fieldNumber)
       {
       case 0 :
         this.value = (j2375.dsrc.asncode.itis.VehicleGroupAffected)value;
         break;
       case 1 :
         this.value = (j2375.dsrc.asncode.itis.ResponderGroupAffected)value;
         break;
       case 2 :
         this.value = (j2375.dsrc.asncode.itis.IncidentResponseEquipment)value;
         break;
       default :
         throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
       }
     }

    /**
     *  Creates and sets a newly allocated component value from this VehicleClass.
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this VehicleClass.
     *  @return a value from a class implementing the IValue interface.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnSetNewChoiceValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.IChoiceNamedType field)
     {
       this.fieldNumber = field.getFieldNumber(context);
       switch (this.fieldNumber)
       {
       case 0 :
         this.value = new j2375.dsrc.asncode.itis.VehicleGroupAffected();
         return this.value;
       case 1 :
         this.value = new j2375.dsrc.asncode.itis.ResponderGroupAffected();
         return this.value;
       case 2 :
         this.value = new j2375.dsrc.asncode.itis.IncidentResponseEquipment();
         return this.value;
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
       }
     }

  }

  /**
   *  Constructs a newly allocated VehicleIdent.
   */
  public VehicleIdent ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this VehicleIdent.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.name;
     case 1 :
       return this.vin;
     case 2 :
       return this.ownerCode;
     case 3 :
       return this.id;
     case 4 :
       return this.vehicleType;
     case 5 :
       return this.vehicleClass;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this VehicleIdent.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this VehicleIdent.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.dsrc.DescriptiveName();
     case 1 :
       return new j2375.dsrc.asncode.dsrc.VINstring();
     case 2 :
       return new fr.marben.asnsdk.japi.spe.IA5StringValue();
     case 3 :
       return new j2375.dsrc.asncode.dsrc.VehicleID();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.VehicleType();
     case 5 :
       return new VehicleClass();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this VehicleIdent.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this VehicleIdent.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.name = new j2375.dsrc.asncode.dsrc.DescriptiveName();
       return this.name;
     case 1 :
       this.vin = new j2375.dsrc.asncode.dsrc.VINstring();
       return this.vin;
     case 2 :
       this.ownerCode = new fr.marben.asnsdk.japi.spe.IA5StringValue();
       return this.ownerCode;
     case 3 :
       this.id = new j2375.dsrc.asncode.dsrc.VehicleID();
       return this.id;
     case 4 :
       this.vehicleType = new j2375.dsrc.asncode.dsrc.VehicleType();
       return this.vehicleType;
     case 5 :
       this.vehicleClass = new VehicleClass();
       return this.vehicleClass;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets a group value from the VehicleIdent.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Returns whether or not this group is present among the extensions.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @return <code>true</code>: when the group is present.
   *          <code>false</code>: when the group is not present.
   */
   public boolean asnIsSetSeqGroupPresent(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated group value of the VehicleIdent.
   *  This group is created for temporary use, in order to solve atNotations.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated group value of the VehicleIdent.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 163;
  }

}
