/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/VerticalOffset.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> vehicle's GPS
 * Class definition of the VerticalOffset type of the dsrc module.
 */
public class VerticalOffset extends fr.marben.asnsdk.japi.spe.ChoiceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 226;

  /**
   * <BR> Vertical Offset
   * <BR> All below in steps of 10cm above or below the reference ellipsoid
   * value of the fieldNumber for the field offset1.
   * <BR>Use {@link j2375.dsrc.asncode.dsrc.VertOffset_B07 j2375.dsrc.asncode.dsrc.VertOffset_B07} for the values of this type.
   */
  public static final short ASN_offset1 = 0;

  /**
   * <BR> with a range of +-   63 meters vertical
   * value of the fieldNumber for the field offset2.
   * <BR>Use {@link j2375.dsrc.asncode.dsrc.VertOffset_B08 j2375.dsrc.asncode.dsrc.VertOffset_B08} for the values of this type.
   */
  public static final short ASN_offset2 = 1;

  /**
   * <BR> with a range of +-  127 meters vertical
   * value of the fieldNumber for the field offset3.
   * <BR>Use {@link j2375.dsrc.asncode.dsrc.VertOffset_B09 j2375.dsrc.asncode.dsrc.VertOffset_B09} for the values of this type.
   */
  public static final short ASN_offset3 = 2;

  /**
   * <BR> with a range of +-  255 meters vertical
   * value of the fieldNumber for the field offset4.
   * <BR>Use {@link j2375.dsrc.asncode.dsrc.VertOffset_B10 j2375.dsrc.asncode.dsrc.VertOffset_B10} for the values of this type.
   */
  public static final short ASN_offset4 = 3;

  /**
   * <BR> with a range of +-  511 meters vertical
   * value of the fieldNumber for the field offset5.
   * <BR>Use {@link j2375.dsrc.asncode.dsrc.VertOffset_B11 j2375.dsrc.asncode.dsrc.VertOffset_B11} for the values of this type.
   */
  public static final short ASN_offset5 = 4;

  /**
   * <BR> with a range of +- 1023 meters vertical
   * value of the fieldNumber for the field offset6.
   * <BR>Use {@link j2375.dsrc.asncode.dsrc.VertOffset_B12 j2375.dsrc.asncode.dsrc.VertOffset_B12} for the values of this type.
   */
  public static final short ASN_offset6 = 5;

  /**
   * <BR> with a range of +- 2047 meters vertical
   * value of the fieldNumber for the field elevation.
   * <BR>Use {@link j2375.dsrc.asncode.dsrc.Elevation j2375.dsrc.asncode.dsrc.Elevation} for the values of this type.
   */
  public static final short ASN_elevation = 6;

  /**
   * <BR> with a range of -4095 to + 61439 meters
   * value of the fieldNumber for the field regional.
   * <BR>Use {@link fr.marben.asnsdk.japi.spe.SequenceValue fr.marben.asnsdk.japi.spe.SequenceValue} for the values of this type.
   */
  public static final short ASN_regional = 7;

  /**
   * class definition of the regional field.
   */
  public static class Regional extends fr.marben.asnsdk.japi.spe.SequenceValue
  {
    /**
     * mandatory field regionId.
     */
    public j2375.dsrc.asncode.dsrc.RegionId regionId;

    /**
     * mandatory field regExtValue.
     */
    public fr.marben.asnsdk.japi.spe.OpenTypeValue regExtValue;

    /**
     *  Constructs a newly allocated Regional.
     */
    public Regional ()
    {
      super();
    };

    /**
     *  Gets the value of a component from this Regional.
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type identifier of the component.
     *  @return the value identified by the named type.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
     {
       switch (field.getFieldNumber(context))
       {
       case 0 :
         return this.regionId;
       case 1 :
         return this.regExtValue;
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
       }
     }

    /**
     *  Creates a newly allocated component value from this Regional.
     *  this value is created for temporary use to solve atNotations
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this Regional.
     *  @return a value from a class implementing the IValue interface.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
     {
       switch (field.getFieldNumber(context))
       {
       case 0 :
         return new j2375.dsrc.asncode.dsrc.RegionId();
       case 1 :
         return new fr.marben.asnsdk.japi.spe.OpenTypeValue();
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
       }
     }

    /**
     *  Creates and sets a newly allocated component value from this Regional.
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this Regional.
     *  @return a value from a class implementing the IValue interface.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
     {
       switch (field.getFieldNumber(context))
       {
       case 0 :
         this.regionId = new j2375.dsrc.asncode.dsrc.RegionId();
         return this.regionId;
       case 1 :
         this.regExtValue = new fr.marben.asnsdk.japi.spe.OpenTypeValue();
         return this.regExtValue;
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
       }
     }

  }

  /**
   *  Constructs a newly allocated VerticalOffset.
   */
  public VerticalOffset ()
  {
    super();
  };

  /**
   *  Create a newly allocated VerticalOffset.
   *  @param fieldNumber the named type identifier of the component.
   *  @param value the value to set.
   *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
   */
   public VerticalOffset(short fieldNumber,
                        fr.marben.asnsdk.japi.spe.Value value)
                        throws fr.marben.asnsdk.japi.InvalidStructureException
   {
     this.fieldNumber = fieldNumber;
     switch (fieldNumber)
     {
     case 0 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B07)value;
       break;
     case 1 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B08)value;
       break;
     case 2 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B09)value;
       break;
     case 3 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B10)value;
       break;
     case 4 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B11)value;
       break;
     case 5 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B12)value;
       break;
     case 6 :
       this.value = (j2375.dsrc.asncode.dsrc.Elevation)value;
       break;
     case 7 :
       this.value = (Regional)value;
       break;
     default :
       throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
     }
   }

  /**
   *  Sets the value of a component from this VerticalOffset.
   *  @param fieldNumber the named type identifier of the component.
   *  @param value the value to set.
   *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
   */
   public void setValue(short fieldNumber,
                        fr.marben.asnsdk.japi.spe.Value value)
                        throws fr.marben.asnsdk.japi.InvalidStructureException
   {
     this.fieldNumber = fieldNumber;
     switch (fieldNumber)
     {
     case 0 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B07)value;
       break;
     case 1 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B08)value;
       break;
     case 2 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B09)value;
       break;
     case 3 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B10)value;
       break;
     case 4 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B11)value;
       break;
     case 5 :
       this.value = (j2375.dsrc.asncode.dsrc.VertOffset_B12)value;
       break;
     case 6 :
       this.value = (j2375.dsrc.asncode.dsrc.Elevation)value;
       break;
     case 7 :
       this.value = (Regional)value;
       break;
     default :
       throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this VerticalOffset.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this VerticalOffset.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewChoiceValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.IChoiceNamedType field)
   {
     this.fieldNumber = field.getFieldNumber(context);
     switch (this.fieldNumber)
     {
     case 0 :
       this.value = new j2375.dsrc.asncode.dsrc.VertOffset_B07();
       return this.value;
     case 1 :
       this.value = new j2375.dsrc.asncode.dsrc.VertOffset_B08();
       return this.value;
     case 2 :
       this.value = new j2375.dsrc.asncode.dsrc.VertOffset_B09();
       return this.value;
     case 3 :
       this.value = new j2375.dsrc.asncode.dsrc.VertOffset_B10();
       return this.value;
     case 4 :
       this.value = new j2375.dsrc.asncode.dsrc.VertOffset_B11();
       return this.value;
     case 5 :
       this.value = new j2375.dsrc.asncode.dsrc.VertOffset_B12();
       return this.value;
     case 6 :
       this.value = new j2375.dsrc.asncode.dsrc.Elevation();
       return this.value;
     case 7 :
       this.value = new Regional();
       return this.value;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 226;
  }

}
