/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/WheelSensorStatus.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the WheelSensorStatus type of the dsrc module.
 */
public class WheelSensorStatus extends fr.marben.asnsdk.japi.spe.EnumeratedValue
{
  /**
   * value of the named enumerated off.
   */
  public static final int ASN_off = 0;

  /**
   * value of the named enumerated on.
   */
  public static final int ASN_on = 1;

  /**
   * value of the named enumerated notDefined.
   */
  public static final int ASN_notDefined = 2;

  /**
   * value of the named enumerated notSupported.
   */
  public static final int ASN_notSupported = 3;

  /**
   *  Constructs a newly allocated WheelSensorStatus.
   */
  public WheelSensorStatus ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated WheelSensorStatus that represents the primitive int argument.
   *  @param value the value to be represented by this WheelSensorStatus.
   */
  public WheelSensorStatus (int value)
  {
    super(value);
  };
}
