/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/WiperRate.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> 
 * <BR> True or False
 * <BR> If "true", the vehicles on this specific connecting 
 * <BR> maneuver have to stop on the stop-line
 * <BR> and not to enter the collision area
 * Class definition of the WiperRate type of the dsrc module.
 */
public class WiperRate extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated WiperRate.
   */
  public WiperRate ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated WiperRate that represents the primitive int argument.
   *  @param value the value to be represented by this WiperRate.
   */
  public WiperRate (int value)
  {
    super(value);
  };
}
