/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/WorkZone.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * Class definition of the WorkZone type of the dsrc module.
 */
public class WorkZone extends fr.marben.asnsdk.japi.spe.SequenceOfValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 222;

  /**
   * class definition of the SEQUENCE field.
   */
  public static class SEQUENCE extends fr.marben.asnsdk.japi.spe.SequenceValue
  {
    /**
     * mandatory field item.
     */
    public Item item;

    /**
     * class definition of the item field.
     */
    public static class Item extends fr.marben.asnsdk.japi.spe.ChoiceValue
    {
      /**
       * value of the fieldNumber for the field itis.
       * <BR>Use {@link j2375.dsrc.asncode.itis.ITIScodes j2375.dsrc.asncode.itis.ITIScodes} for the values of this type.
       */
      public static final short ASN_itis = 0;

      /**
       * value of the fieldNumber for the field text.
       * <BR>Use {@link j2375.dsrc.asncode.dsrc.ITIStextPhrase j2375.dsrc.asncode.dsrc.ITIStextPhrase} for the values of this type.
       */
      public static final short ASN_text = 1;

      /**
       *  Constructs a newly allocated Item.
       */
      public Item ()
      {
        super();
      };

      /**
       *  Create a newly allocated Item.
       *  @param fieldNumber the named type identifier of the component.
       *  @param value the value to set.
       *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
       */
       public Item(short fieldNumber,
                            fr.marben.asnsdk.japi.spe.Value value)
                            throws fr.marben.asnsdk.japi.InvalidStructureException
       {
         this.fieldNumber = fieldNumber;
         switch (fieldNumber)
         {
         case 0 :
           this.value = (j2375.dsrc.asncode.itis.ITIScodes)value;
           break;
         case 1 :
           this.value = (j2375.dsrc.asncode.dsrc.ITIStextPhrase)value;
           break;
         default :
           throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
         }
       }

      /**
       *  Sets the value of a component from this Item.
       *  @param fieldNumber the named type identifier of the component.
       *  @param value the value to set.
       *  @throws fr.marben.asnsdk.japi.InvalidStructureException in case of a problem
       */
       public void setValue(short fieldNumber,
                            fr.marben.asnsdk.japi.spe.Value value)
                            throws fr.marben.asnsdk.japi.InvalidStructureException
       {
         this.fieldNumber = fieldNumber;
         switch (fieldNumber)
         {
         case 0 :
           this.value = (j2375.dsrc.asncode.itis.ITIScodes)value;
           break;
         case 1 :
           this.value = (j2375.dsrc.asncode.dsrc.ITIStextPhrase)value;
           break;
         default :
           throw new fr.marben.asnsdk.japi.InvalidStructureException(fr.marben.asnsdk.japi.InvalidStructureException.INVALID_CHOICE_ALTERNATIVE);
         }
       }

      /**
       *  Creates and sets a newly allocated component value from this Item.
       *  This method is only for ASNSDK internal use.
       *  @param context a fr.marben.asnsdk.japi.Context.
       *  @param field the named type of this Item.
       *  @return a value from a class implementing the IValue interface.
       */
       public fr.marben.asnsdk.japi.vi.IValue asnSetNewChoiceValue(
                               fr.marben.asnsdk.japi.Context context,
                               fr.marben.asnsdk.japi.vi.IChoiceNamedType field)
       {
         this.fieldNumber = field.getFieldNumber(context);
         switch (this.fieldNumber)
         {
         case 0 :
           this.value = new j2375.dsrc.asncode.itis.ITIScodes();
           return this.value;
         case 1 :
           this.value = new j2375.dsrc.asncode.dsrc.ITIStextPhrase();
           return this.value;
         default :
           throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
         }
       }

    }

    /**
     *  Constructs a newly allocated SEQUENCE.
     */
    public SEQUENCE ()
    {
      super();
    };

    /**
     *  Gets the value of a component from this SEQUENCE.
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type identifier of the component.
     *  @return the value identified by the named type.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
     {
       switch (field.getFieldNumber(context))
       {
       case 0 :
         return this.item;
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
       }
     }

    /**
     *  Creates a newly allocated component value from this SEQUENCE.
     *  this value is created for temporary use to solve atNotations
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this SEQUENCE.
     *  @return a value from a class implementing the IValue interface.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
     {
       switch (field.getFieldNumber(context))
       {
       case 0 :
         return new Item();
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
       }
     }

    /**
     *  Creates and sets a newly allocated component value from this SEQUENCE.
     *  This method is only for ASNSDK internal use.
     *  @param context a fr.marben.asnsdk.japi.Context.
     *  @param field the named type of this SEQUENCE.
     *  @return a value from a class implementing the IValue interface.
     */
     public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                             fr.marben.asnsdk.japi.Context context,
                             fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
     {
       switch (field.getFieldNumber(context))
       {
       case 0 :
         this.item = new Item();
         return this.item;
       default :
         throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
       }
     }

  }

  /**
   *  Constructs a newly allocated WorkZone.
   */
  public WorkZone ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated WorkZone with the given list.
   *  @param list the list used to initialize this WorkZone.
   */
  public WorkZone (java.util.List list)
  {
    super(list);
  };
  
  /**
   *  Creates and appends a newly allocated component value from 
   *  this WorkZone.
   *  This method is only for ASNSDK internal use. 
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this WorkZone.
   *  @return a value from a class implementing de IValue interface.
   */
  public fr.marben.asnsdk.japi.vi.IValue asnAddNewSetSeqOfValue(
                        fr.marben.asnsdk.japi.Context context,
                        fr.marben.asnsdk.japi.vi.ISetSeqOfNamedType field)
  {
        j2375.dsrc.asncode.dsrc.WorkZone.SEQUENCE value = new j2375.dsrc.asncode.dsrc.WorkZone.SEQUENCE();
        this.valueList.add(value);
        return value;
  }
  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 222;
  }

}
