/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/dsrc/Zoom.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.dsrc;

/**
 * <BR> Unit = 1 meter, 0 = unknown, 
 * <BR> The value 10000 to be used for Distances >=10000 m
 * <BR> (eg from known point to another point along a 
 * <BR> known path, often against traffic flow direction 
 * <BR> when used for measuring queues)
 * Class definition of the Zoom type of the dsrc module.
 */
public class Zoom extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated Zoom.
   */
  public Zoom ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated Zoom that represents the primitive int argument.
   *  @param value the value to be represented by this Zoom.
   */
  public Zoom (int value)
  {
    super(value);
  };
}
