/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/ValueFactory.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode;

/**
 * Value Factory class definition.
 */
public class ValueFactory extends fr.marben.asnsdk.japi.spe.ValueFactory
{
  /**
   *  (ASNSDK internal use only) Creates a value of the type identified by the type assignment.
   *  @param context the thread context
   *  @param typeAss the type assignment identifying the type.
   *  @return a value of the type identified by the type assignment.
   */
  public fr.marben.asnsdk.japi.vi.IValue asnCreateValue(
         fr.marben.asnsdk.japi.Context context, 
         fr.marben.asnsdk.japi.vi.ITypeAssignment typeAss) 
  {
    switch (typeAss.getTypeIndex(context))
    {
      case 31:
        return new j2375.dsrc.asncode.dsrc.AccelSteerYawRateConfidence();
      case 32:
        return new j2375.dsrc.asncode.dsrc.AccelerationSet4Way();
      case 33:
        return new j2375.dsrc.asncode.dsrc.AdvisorySpeed();
      case 34:
        return new j2375.dsrc.asncode.dsrc.AdvisorySpeedList();
      case 35:
        return new j2375.dsrc.asncode.dsrc.AntennaOffsetSet();
      case 36:
        return new j2375.dsrc.asncode.dsrc.ApproachOrLane();
      case 37:
        return new j2375.dsrc.asncode.dsrc.AxleWeightList();
      case 38:
        return new j2375.dsrc.asncode.dsrc.AxleWeightSet();
      case 39:
        return new j2375.dsrc.asncode.dsrc.BSMcoreData();
      case 43:
        return new j2375.dsrc.asncode.dsrc.BasicSafetyMessage();
      case 41:
        return new j2375.dsrc.asncode.dsrc.BrakeSystemStatus();
      case 44:
        return new j2375.dsrc.asncode.dsrc.BumperHeights();
      case 45:
        return new j2375.dsrc.asncode.dsrc.Circle();
      case 47:
        return new j2375.dsrc.asncode.dsrc.CodeWord();
      case 48:
        return new j2375.dsrc.asncode.dsrc.CommonSafetyRequest();
      case 50:
        return new j2375.dsrc.asncode.dsrc.ComputedLane();
      case 51:
        return new j2375.dsrc.asncode.dsrc.ConfidenceSet();
      case 54:
        return new j2375.dsrc.asncode.dsrc.ConnectingLane();
      case 55:
        return new j2375.dsrc.asncode.dsrc.Connection();
      case 57:
        return new j2375.dsrc.asncode.dsrc.ConnectionManeuverAssist();
      case 58:
        return new j2375.dsrc.asncode.dsrc.ConnectsToList();
      case 59:
        return new j2375.dsrc.asncode.dsrc.Count();
      case 60:
        return new j2375.dsrc.asncode.dsrc.DDate();
      case 61:
        return new j2375.dsrc.asncode.dsrc.DDateTime();
      case 62:
        return new j2375.dsrc.asncode.dsrc.DFullTime();
      case 63:
        return new j2375.dsrc.asncode.dsrc.DMonthDay();
      case 64:
        return new j2375.dsrc.asncode.dsrc.DTime();
      case 65:
        return new j2375.dsrc.asncode.dsrc.DYearMonth();
      case 66:
        return new j2375.dsrc.asncode.dsrc.DataParameters();
      case 67:
        return new j2375.dsrc.asncode.dsrc.DisabledVehicle();
      case 68:
        return new j2375.dsrc.asncode.dsrc.Duration();
      case 69:
        return new j2375.dsrc.asncode.dsrc.EmergencyDetails();
      case 71:
        return new j2375.dsrc.asncode.dsrc.EmergencyVehicleAlert();
      case 75:
        return new j2375.dsrc.asncode.dsrc.EnabledLaneList();
      case 76:
        return new j2375.dsrc.asncode.dsrc.EventDescription();
      case 77:
        return new j2375.dsrc.asncode.dsrc.ExitService();
      case 73:
        return new j2375.dsrc.asncode.dsrc.FullPositionVector();
      case 78:
        return new j2375.dsrc.asncode.dsrc.GenericLane();
      case 92:
        return new j2375.dsrc.asncode.dsrc.GenericSignage();
      case 93:
        return new j2375.dsrc.asncode.dsrc.GeographicalPath();
      case 109:
        return new j2375.dsrc.asncode.dsrc.GeometricProjection();
      case 115:
        return new j2375.dsrc.asncode.dsrc.Header();
      case 116:
        return new j2375.dsrc.asncode.dsrc.IntersectionAccessPoint();
      case 117:
        return new j2375.dsrc.asncode.dsrc.IntersectionCollision();
      case 122:
        return new j2375.dsrc.asncode.dsrc.IntersectionGeometry();
      case 126:
        return new j2375.dsrc.asncode.dsrc.IntersectionGeometryList();
      case 56:
        return new j2375.dsrc.asncode.dsrc.IntersectionReferenceID();
      case 127:
        return new j2375.dsrc.asncode.dsrc.IntersectionState();
      case 134:
        return new j2375.dsrc.asncode.dsrc.IntersectionStateList();
      case 135:
        return new j2375.dsrc.asncode.dsrc.J1939data();
      case 79:
        return new j2375.dsrc.asncode.dsrc.LaneAttributes();
      case 88:
        return new j2375.dsrc.asncode.dsrc.LaneDataAttribute();
      case 87:
        return new j2375.dsrc.asncode.dsrc.LaneDataAttributeList();
      case 123:
        return new j2375.dsrc.asncode.dsrc.LaneList();
      case 80:
        return new j2375.dsrc.asncode.dsrc.LaneTypeAttributes();
      case 138:
        return new j2375.dsrc.asncode.dsrc.Location_quality();
      case 139:
        return new j2375.dsrc.asncode.dsrc.Location_tech();
      case 133:
        return new j2375.dsrc.asncode.dsrc.ManeuverAssistList();
      case 140:
        return new j2375.dsrc.asncode.dsrc.MapData();
      case 148:
        return new j2375.dsrc.asncode.dsrc.MessageBLOB();
      case 149:
        return new j2375.dsrc.asncode.dsrc.MessageFrame();
      case 131:
        return new j2375.dsrc.asncode.dsrc.MovementEvent();
      case 130:
        return new j2375.dsrc.asncode.dsrc.MovementEventList();
      case 128:
        return new j2375.dsrc.asncode.dsrc.MovementList();
      case 129:
        return new j2375.dsrc.asncode.dsrc.MovementState();
      case 150:
        return new j2375.dsrc.asncode.dsrc.NMEAcorrections();
      case 100:
        return new j2375.dsrc.asncode.dsrc.Node_LL_24B();
      case 101:
        return new j2375.dsrc.asncode.dsrc.Node_LL_28B();
      case 102:
        return new j2375.dsrc.asncode.dsrc.Node_LL_32B();
      case 103:
        return new j2375.dsrc.asncode.dsrc.Node_LL_36B();
      case 104:
        return new j2375.dsrc.asncode.dsrc.Node_LL_44B();
      case 105:
        return new j2375.dsrc.asncode.dsrc.Node_LL_48B();
      case 22:
        return new j2375.dsrc.asncode.dsrc.Node_LLmD_64b();
      case 16:
        return new j2375.dsrc.asncode.dsrc.Node_XY_20b();
      case 17:
        return new j2375.dsrc.asncode.dsrc.Node_XY_22b();
      case 18:
        return new j2375.dsrc.asncode.dsrc.Node_XY_24b();
      case 19:
        return new j2375.dsrc.asncode.dsrc.Node_XY_26b();
      case 20:
        return new j2375.dsrc.asncode.dsrc.Node_XY_28b();
      case 21:
        return new j2375.dsrc.asncode.dsrc.Node_XY_32b();
      case 107:
        return new j2375.dsrc.asncode.dsrc.NodeAttributeLLList();
      case 106:
        return new j2375.dsrc.asncode.dsrc.NodeAttributeSetLL();
      case 84:
        return new j2375.dsrc.asncode.dsrc.NodeAttributeSetXY();
      case 85:
        return new j2375.dsrc.asncode.dsrc.NodeAttributeXYList();
      case 98:
        return new j2375.dsrc.asncode.dsrc.NodeLL();
      case 96:
        return new j2375.dsrc.asncode.dsrc.NodeListLL();
      case 81:
        return new j2375.dsrc.asncode.dsrc.NodeListXY();
      case 99:
        return new j2375.dsrc.asncode.dsrc.NodeOffsetPointLL();
      case 15:
        return new j2375.dsrc.asncode.dsrc.NodeOffsetPointXY();
      case 97:
        return new j2375.dsrc.asncode.dsrc.NodeSetLL();
      case 82:
        return new j2375.dsrc.asncode.dsrc.NodeSetXY();
      case 83:
        return new j2375.dsrc.asncode.dsrc.NodeXY();
      case 151:
        return new j2375.dsrc.asncode.dsrc.ObstacleDetection();
      case 95:
        return new j2375.dsrc.asncode.dsrc.OffsetSystem();
      case 91:
        return new j2375.dsrc.asncode.dsrc.OverlayLaneList();
      case 118:
        return new j2375.dsrc.asncode.dsrc.PathHistory();
      case 120:
        return new j2375.dsrc.asncode.dsrc.PathHistoryPoint();
      case 119:
        return new j2375.dsrc.asncode.dsrc.PathHistoryPointList();
      case 121:
        return new j2375.dsrc.asncode.dsrc.PathPrediction();
      case 152:
        return new j2375.dsrc.asncode.dsrc.PayloadData();
      case 153:
        return new j2375.dsrc.asncode.dsrc.PersonalSafetyMessage();
      case 155:
        return new j2375.dsrc.asncode.dsrc.PivotPointDescription();
      case 46:
        return new j2375.dsrc.asncode.dsrc.Position3D();
      case 53:
        return new j2375.dsrc.asncode.dsrc.PositionConfidenceSet();
      case 40:
        return new j2375.dsrc.asncode.dsrc.PositionalAccuracy();
      case 124:
        return new j2375.dsrc.asncode.dsrc.PreemptPriorityList();
      case 70:
        return new j2375.dsrc.asncode.dsrc.PrivilegedEvents();
      case 156:
        return new j2375.dsrc.asncode.dsrc.ProbeDataManagement();
      case 162:
        return new j2375.dsrc.asncode.dsrc.ProbeVehicleData();
      case 154:
        return new j2375.dsrc.asncode.dsrc.PropelledInformation();
      case 170:
        return new j2375.dsrc.asncode.dsrc.RTCMPackage();
      case 173:
        return new j2375.dsrc.asncode.dsrc.RTCMcorrections();
      case 171:
        return new j2375.dsrc.asncode.dsrc.RTCMheader();
      case 172:
        return new j2375.dsrc.asncode.dsrc.RTCMmessageList();
      case 113:
        return new j2375.dsrc.asncode.dsrc.RegionList();
      case 114:
        return new j2375.dsrc.asncode.dsrc.RegionOffsets();
      case 112:
        return new j2375.dsrc.asncode.dsrc.RegionPointSet();
      case 90:
        return new j2375.dsrc.asncode.dsrc.RegulatorySpeedLimit();
      case 49:
        return new j2375.dsrc.asncode.dsrc.RequestedItemList();
      case 174:
        return new j2375.dsrc.asncode.dsrc.RequestorDescription();
      case 176:
        return new j2375.dsrc.asncode.dsrc.RequestorPositionVector();
      case 175:
        return new j2375.dsrc.asncode.dsrc.RequestorType();
      case 145:
        return new j2375.dsrc.asncode.dsrc.RestrictionClassAssignment();
      case 144:
        return new j2375.dsrc.asncode.dsrc.RestrictionClassList();
      case 147:
        return new j2375.dsrc.asncode.dsrc.RestrictionUserType();
      case 146:
        return new j2375.dsrc.asncode.dsrc.RestrictionUserTypeList();
      case 143:
        return new j2375.dsrc.asncode.dsrc.RoadLaneSetList();
      case 142:
        return new j2375.dsrc.asncode.dsrc.RoadSegment();
      case 141:
        return new j2375.dsrc.asncode.dsrc.RoadSegmentList();
      case 94:
        return new j2375.dsrc.asncode.dsrc.RoadSegmentReferenceID();
      case 72:
        return new j2375.dsrc.asncode.dsrc.RoadSideAlert();
      case 177:
        return new j2375.dsrc.asncode.dsrc.RoadSignID();
      case 178:
        return new j2375.dsrc.asncode.dsrc.SPAT();
      case 157:
        return new j2375.dsrc.asncode.dsrc.Sample();
      case 108:
        return new j2375.dsrc.asncode.dsrc.SegmentAttributeLLList();
      case 86:
        return new j2375.dsrc.asncode.dsrc.SegmentAttributeXYList();
      case 111:
        return new j2375.dsrc.asncode.dsrc.ShapePointSet();
      case 125:
        return new j2375.dsrc.asncode.dsrc.SignalControlZone();
      case 179:
        return new j2375.dsrc.asncode.dsrc.SignalReqScheme();
      case 180:
        return new j2375.dsrc.asncode.dsrc.SignalRequest();
      case 181:
        return new j2375.dsrc.asncode.dsrc.SignalRequestList();
      case 183:
        return new j2375.dsrc.asncode.dsrc.SignalRequestMessage();
      case 182:
        return new j2375.dsrc.asncode.dsrc.SignalRequestPackage();
      case 184:
        return new j2375.dsrc.asncode.dsrc.SignalRequesterInfo();
      case 185:
        return new j2375.dsrc.asncode.dsrc.SignalStatus();
      case 188:
        return new j2375.dsrc.asncode.dsrc.SignalStatusList();
      case 189:
        return new j2375.dsrc.asncode.dsrc.SignalStatusMessage();
      case 187:
        return new j2375.dsrc.asncode.dsrc.SignalStatusPackage();
      case 186:
        return new j2375.dsrc.asncode.dsrc.SignalStatusPackageList();
      case 166:
        return new j2375.dsrc.asncode.dsrc.Snapshot();
      case 159:
        return new j2375.dsrc.asncode.dsrc.SnapshotDistance();
      case 158:
        return new j2375.dsrc.asncode.dsrc.SnapshotTime();
      case 190:
        return new j2375.dsrc.asncode.dsrc.SpecialVehicleExtensions();
      case 196:
        return new j2375.dsrc.asncode.dsrc.SpeedLimit();
      case 89:
        return new j2375.dsrc.asncode.dsrc.SpeedLimitList();
      case 197:
        return new j2375.dsrc.asncode.dsrc.SpeedProfile();
      case 198:
        return new j2375.dsrc.asncode.dsrc.SpeedProfileMeasurementList();
      case 52:
        return new j2375.dsrc.asncode.dsrc.SpeedandHeadingandThrottleConfidence();
      case 199:
        return new j2375.dsrc.asncode.dsrc.SupplementalVehicleExtensions();
      case 203:
        return new j2375.dsrc.asncode.dsrc.TestMessage00();
      case 204:
        return new j2375.dsrc.asncode.dsrc.TestMessage01();
      case 205:
        return new j2375.dsrc.asncode.dsrc.TestMessage02();
      case 206:
        return new j2375.dsrc.asncode.dsrc.TestMessage03();
      case 207:
        return new j2375.dsrc.asncode.dsrc.TestMessage04();
      case 208:
        return new j2375.dsrc.asncode.dsrc.TestMessage05();
      case 209:
        return new j2375.dsrc.asncode.dsrc.TestMessage06();
      case 210:
        return new j2375.dsrc.asncode.dsrc.TestMessage07();
      case 211:
        return new j2375.dsrc.asncode.dsrc.TestMessage08();
      case 212:
        return new j2375.dsrc.asncode.dsrc.TestMessage09();
      case 213:
        return new j2375.dsrc.asncode.dsrc.TestMessage10();
      case 214:
        return new j2375.dsrc.asncode.dsrc.TestMessage11();
      case 215:
        return new j2375.dsrc.asncode.dsrc.TestMessage12();
      case 216:
        return new j2375.dsrc.asncode.dsrc.TestMessage13();
      case 217:
        return new j2375.dsrc.asncode.dsrc.TestMessage14();
      case 218:
        return new j2375.dsrc.asncode.dsrc.TestMessage15();
      case 132:
        return new j2375.dsrc.asncode.dsrc.TimeChangeDetails();
      case 137:
        return new j2375.dsrc.asncode.dsrc.TireData();
      case 136:
        return new j2375.dsrc.asncode.dsrc.TireDataList();
      case 191:
        return new j2375.dsrc.asncode.dsrc.TrailerData();
      case 195:
        return new j2375.dsrc.asncode.dsrc.TrailerHistoryPoint();
      case 194:
        return new j2375.dsrc.asncode.dsrc.TrailerHistoryPointList();
      case 193:
        return new j2375.dsrc.asncode.dsrc.TrailerUnitDescription();
      case 192:
        return new j2375.dsrc.asncode.dsrc.TrailerUnitDescriptionList();
      case 219:
        return new j2375.dsrc.asncode.dsrc.TransitStatus();
      case 74:
        return new j2375.dsrc.asncode.dsrc.TransmissionAndSpeed();
      case 220:
        return new j2375.dsrc.asncode.dsrc.TravelerDataFrame();
      case 223:
        return new j2375.dsrc.asncode.dsrc.TravelerDataFrameList();
      case 224:
        return new j2375.dsrc.asncode.dsrc.TravelerInformation();
      case 225:
        return new j2375.dsrc.asncode.dsrc.URL_Link();
      case 110:
        return new j2375.dsrc.asncode.dsrc.ValidRegion();
      case 165:
        return new j2375.dsrc.asncode.dsrc.VehicleClassification();
      case 200:
        return new j2375.dsrc.asncode.dsrc.VehicleData();
      case 164:
        return new j2375.dsrc.asncode.dsrc.VehicleID();
      case 163:
        return new j2375.dsrc.asncode.dsrc.VehicleIdent();
      case 167:
        return new j2375.dsrc.asncode.dsrc.VehicleSafetyExtensions();
      case 42:
        return new j2375.dsrc.asncode.dsrc.VehicleSize();
      case 168:
        return new j2375.dsrc.asncode.dsrc.VehicleStatus();
      case 161:
        return new j2375.dsrc.asncode.dsrc.VehicleStatusRequest();
      case 160:
        return new j2375.dsrc.asncode.dsrc.VehicleStatusRequestList();
      case 226:
        return new j2375.dsrc.asncode.dsrc.VerticalOffset();
      case 202:
        return new j2375.dsrc.asncode.dsrc.WeatherProbe();
      case 201:
        return new j2375.dsrc.asncode.dsrc.WeatherReport();
      case 169:
        return new j2375.dsrc.asncode.dsrc.WiperSet();
      case 222:
        return new j2375.dsrc.asncode.dsrc.WorkZone();
      case 11:
        return new j2375.dsrc.asncode.addgrpc.Altitude();
      case 12:
        return new j2375.dsrc.asncode.addgrpc.ConnectionManeuverAssist_addGrpC();
      case 23:
        return new j2375.dsrc.asncode.addgrpc.IntersectionState_addGrpC();
      case 26:
        return new j2375.dsrc.asncode.addgrpc.MapData_addGrpC();
      case 29:
        return new j2375.dsrc.asncode.addgrpc.Position3D_addGrpC();
      case 25:
        return new j2375.dsrc.asncode.addgrpc.PrioritizationResponse();
      case 24:
        return new j2375.dsrc.asncode.addgrpc.PrioritizationResponseList();
      case 30:
        return new j2375.dsrc.asncode.addgrpc.RestrictionUserType_addGrpC();
      case 28:
        return new j2375.dsrc.asncode.addgrpc.SignalHeadLocation();
      case 27:
        return new j2375.dsrc.asncode.addgrpc.SignalHeadLocationList();
      case 14:
        return new j2375.dsrc.asncode.addgrpc.VehicleToLanePosition();
      case 13:
        return new j2375.dsrc.asncode.addgrpc.VehicleToLanePositionList();
      case 0:
        return new j2375.dsrc.asncode.addgrpb.Angle();
      case 1:
        return new j2375.dsrc.asncode.addgrpb.LaneDataAttribute_addGrpB();
      case 2:
        return new j2375.dsrc.asncode.addgrpb.LatitudeDMS2();
      case 3:
        return new j2375.dsrc.asncode.addgrpb.LongitudeDMS2();
      case 4:
        return new j2375.dsrc.asncode.addgrpb.MovementEvent_addGrpB();
      case 5:
        return new j2375.dsrc.asncode.addgrpb.MsgCount();
      case 6:
        return new j2375.dsrc.asncode.addgrpb.Node_LLdms_48b();
      case 7:
        return new j2375.dsrc.asncode.addgrpb.Node_LLdms_80b();
      case 8:
        return new j2375.dsrc.asncode.addgrpb.NodeOffsetPointXY_addGrpB();
      case 9:
        return new j2375.dsrc.asncode.addgrpb.Position3D_addGrpB();
      case 10:
        return new j2375.dsrc.asncode.addgrpb.TimeMark();
      case 221:
        return new j2375.dsrc.asncode.itis.ITIScodesAndText();
      default:
        throw new fr.marben.asnsdk.japi.DysfunctionException(
             fr.marben.asnsdk.japi.DysfunctionException.UNKNOWN_TYPE_VALUE);
    }
  }
}
