/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/addgrpb/LatitudeDMS.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.addgrpb;

/**
 * <BR> BCD coding of Hour of a Day, in 1 octet
 * <BR> values above upper nibble 0010 and lower nibble 0100 shall not be sent
 * <BR> values with lower nibble values between 1010 and 1111 shall not be sent
 * <BR> except that the value 255 (0xFF) shall indicate an invalid value
 * Class definition of the LatitudeDMS type of the addgrpb module.
 */
public class LatitudeDMS extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated LatitudeDMS.
   */
  public LatitudeDMS ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated LatitudeDMS that represents the primitive int argument.
   *  @param value the value to be represented by this LatitudeDMS.
   */
  public LatitudeDMS (int value)
  {
    super(value);
  };
}
