/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/addgrpb/MaxTimetoChange.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.addgrpb;

/**
 * <BR> Signed units of 001 seconds of a minute of a degree of Longitude
 * <BR> Providing a range of plus-minus 180 degrees
 * <BR> in a 4 octet value when implicit or in BER forms
 * <BR> the value 0x7FFF FFFF shall indicate an invalid value
 * Class definition of the MaxTimetoChange type of the addgrpb module.
 */
public class MaxTimetoChange extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated MaxTimetoChange.
   */
  public MaxTimetoChange ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated MaxTimetoChange that represents the primitive int argument.
   *  @param value the value to be represented by this MaxTimetoChange.
   */
  public MaxTimetoChange (int value)
  {
    super(value);
  };
}
