/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/addgrpb/Minute.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.addgrpb;

/**
 * <BR> Unsigned units of 01 seconds, in 2 octets
 * <BR> the value 2401 shall indicate 'forever'
 * <BR> the values 2402 to 32766 shall not be sent
 * <BR> the value 32767(0x7FFF) shall indicate an invalid value
 * <BR> Note that:
 * <BR> The MSB is used as a flag and set to one to
 * <BR> indicate that the value does not count down
 * <BR> Under this condition the movement phase may end
 * <BR> immediately if certain condition are meet
 * Class definition of the Minute type of the addgrpb module.
 */
public class Minute extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated Minute.
   */
  public Minute ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated Minute that represents the primitive int argument.
   *  @param value the value to be represented by this Minute.
   */
  public Minute (int value)
  {
    super(value);
  };
}
