/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/addgrpb/MovementEvent_addGrpB.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.addgrpb;

/**
 * Class definition of the MovementEvent_addGrpB type of the addgrpb module.
 */
public class MovementEvent_addGrpB extends fr.marben.asnsdk.japi.spe.ExtSequenceValue
{
  /**
   * value of the typeIndex field for this class.
   */
  public static final int ASNTYPE = 4;

  /**
   * <BR> A set of countdown style time-to-change values
   * <BR> all in units of 01 seconds and following
   * <BR> the naming of the base DSRC standard
   * optional field startTime.
   */
  public j2375.dsrc.asncode.addgrpb.TimeRemaining startTime;

  /**
   * <BR> When this phase 1st started
   * mandatory field minEndTime.
   */
  public j2375.dsrc.asncode.addgrpb.MinTimetoChange minEndTime;

  /**
   * <BR> Expected shortest end time
   * optional field maxEndTime.
   */
  public j2375.dsrc.asncode.addgrpb.MaxTimetoChange maxEndTime;

  /**
   * <BR> Expected longest end time
   * optional field likelyTime.
   */
  public j2375.dsrc.asncode.addgrpb.TimeRemaining likelyTime;

  /**
   * <BR> Best predicted value based on other data             
   * optional field confidence.
   */
  public j2375.dsrc.asncode.dsrc.TimeIntervalConfidence confidence;

  /**
   * <BR> Applies to above time element only
   * optional field nextTime.
   */
  public j2375.dsrc.asncode.addgrpb.TimeRemaining nextTime;

  /**
   *  Constructs a newly allocated MovementEvent_addGrpB.
   */
  public MovementEvent_addGrpB ()
  {
    super();
  };

  /**
   *  Gets the value of a component from this MovementEvent_addGrpB.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type identifier of the component.
   *  @return the value identified by the named type.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return this.startTime;
     case 1 :
       return this.minEndTime;
     case 2 :
       return this.maxEndTime;
     case 3 :
       return this.likelyTime;
     case 4 :
       return this.confidence;
     case 5 :
       return this.nextTime;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to set field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated component value from this MovementEvent_addGrpB.
   *  this value is created for temporary use to solve atNotations
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this MovementEvent_addGrpB.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       return new j2375.dsrc.asncode.addgrpb.TimeRemaining();
     case 1 :
       return new j2375.dsrc.asncode.addgrpb.MinTimetoChange();
     case 2 :
       return new j2375.dsrc.asncode.addgrpb.MaxTimetoChange();
     case 3 :
       return new j2375.dsrc.asncode.addgrpb.TimeRemaining();
     case 4 :
       return new j2375.dsrc.asncode.dsrc.TimeIntervalConfidence();
     case 5 :
       return new j2375.dsrc.asncode.addgrpb.TimeRemaining();
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated component value from this MovementEvent_addGrpB.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param field the named type of this MovementEvent_addGrpB.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqValue(
                           fr.marben.asnsdk.japi.Context context,
                           fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (field.getFieldNumber(context))
     {
     case 0 :
       this.startTime = new j2375.dsrc.asncode.addgrpb.TimeRemaining();
       return this.startTime;
     case 1 :
       this.minEndTime = new j2375.dsrc.asncode.addgrpb.MinTimetoChange();
       return this.minEndTime;
     case 2 :
       this.maxEndTime = new j2375.dsrc.asncode.addgrpb.MaxTimetoChange();
       return this.maxEndTime;
     case 3 :
       this.likelyTime = new j2375.dsrc.asncode.addgrpb.TimeRemaining();
       return this.likelyTime;
     case 4 :
       this.confidence = new j2375.dsrc.asncode.dsrc.TimeIntervalConfidence();
       return this.confidence;
     case 5 :
       this.nextTime = new j2375.dsrc.asncode.addgrpb.TimeRemaining();
       return this.nextTime;
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to create field number " + field.getFieldNumber(context));
     }
   }

  /**
   *  Gets a group value from the MovementEvent_addGrpB.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnGetSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Returns whether or not this group is present among the extensions.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @return <code>true</code>: when the group is present.
   *          <code>false</code>: when the group is not present.
   */
   public boolean asnIsSetSeqGroupPresent(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates a newly allocated group value of the MovementEvent_addGrpB.
   *  This group is created for temporary use, in order to solve atNotations.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewTmpSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Creates and sets a newly allocated group value of the MovementEvent_addGrpB.
   *  This method is only for ASNSDK internal use.
   *  @param context a fr.marben.asnsdk.japi.Context.
   *  @param group the extension group.
   *  @param field the named type of the extension group.
   *  @return a value from a class implementing the IValue interface.
   */
   public fr.marben.asnsdk.japi.vi.IValue asnSetNewSetSeqGroupValue(fr.marben.asnsdk.japi.Context context,
                                fr.marben.asnsdk.japi.vi.ISetSeqExtensionGroup group,
                                fr.marben.asnsdk.japi.vi.ISetSeqNamedType field)
   {
     switch (group.getFieldNumber(context))
     {
     default :
       throw new fr.marben.asnsdk.japi.DysfunctionException("Unable to find the group " + group.getFieldNumber(context));
     }
   }

  /**
   *  Gets the typeIndex value for this class.
   *  This method is only for ASNSDK internal use. 
   *  @return the type index.
   */
  public int asnGetTypeIndex()
  {
    return 4;
  }

}
