/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/addgrpb/TenthSecond.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.addgrpb;

/**
 * <BR> Encoding as per above, in 1 bit
 * Class definition of the TenthSecond type of the addgrpb module.
 */
public class TenthSecond extends fr.marben.asnsdk.japi.spe.IntIntegerValue
{
  /**
   *  Constructs a newly allocated TenthSecond.
   */
  public TenthSecond ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated TenthSecond that represents the primitive int argument.
   *  @param value the value to be represented by this TenthSecond.
   */
  public TenthSecond (int value)
  {
    super(value);
  };
}
