/*
Copyright (C) 1999-2011 Marben Products. All rights reserved.

THIS FILE IS PROPRIETARY MATERIAL OF MARBEN PRODUCTS.
AND MAY BE USED ONLY BY DIRECT LICENSEES OF ASNSDK PRODUCT.
THIS FILE MAY NOT BE DISTRIBUTED.

===========================================================================

/home/itsrc/J2375_2016/src/asncode/itis/ITIStext.java: 

Generated by ASNSDK TCE-JAVA ASN.1 Compiler v4.0 - REF_8.55 - REF_8.39

===========================================================================
*/
package j2375.dsrc.asncode.itis;

/**
 * Class definition of the ITIStext type of the itis module.
 */
public class ITIStext extends fr.marben.asnsdk.japi.spe.IA5StringValue
{
  /**
   *  Constructs a newly allocated ITIStext.
   */
  public ITIStext ()
  {
    super();
  };

  /**
   *  Constructs a newly allocated ITIStext that represents the primitive string argument.
   *  @param value the value to be represented by this ITIStext.
   */
  public ITIStext (java.lang.String value)
  {
    super(value);
  };
}
